### ISSUE TITLE
enable lang and apple-mobile-web-app-status-bar-style options

### ISSUE THREAD

**Issue by imdanielpiva** [jantimon/favicons-webpack-plugin#100]
Hi, there! I'm having some problems with the current plugin configuration, because I'm not able to automate it to generate the manifest with all the options I want, which, in this case, are the language and the apple-mobile-web-app-status-bar-style meta tag.

The plugin uses english as its deafult language and the meta tag for the ios status bar uses 'black-translucent', which is deprecated, and causes some problems for me, then every new production build I have to change it manually. Please, it would be awesome if you or someone else could help me, thanks!

**Comment by imdanielpiva** [comment]
yep, I figured this out :)
even though this plugin is really useful!

**Comment by devourment77** [comment]
@imdanielpiva did you actually find the attribute needed for `apple-mobile-web-app-status-bar-style` ?

**Comment by imdanielpiva** [comment]
@devourment77 nope!
after some digging into the code, I found out that it had to do with the main lib behind the plugin: `favicons`. so at the time I just forked the project for the company I was working on because I really needed it to get working.

I just also found out that the `favicons` people just [fixed](https://github.com/itgalaxy/favicons/issues/230) this bug. Apparently, it would be just like that:

```javascrip
{
  "path": "/",
  "appName": null,
  "appDescription": null,
  "developerName": null,
  "developerURL": null,
  "dir": "auto",
  "lang": "en-US",
  "background": "#fff",
  "theme_color": "#fff",

  // just set the "appleStatusBarStyle" prop and it's fine
  "appleStatusBarStyle": "black-translucent",

  ...
}
```
