### ISSUE TITLE
How to disable application-name meta tag insertion? [feature-request]

### ISSUE THREAD

**Issue by damianobarbati** [jantimon/favicons-webpack-plugin#102]
The plugin is adding the following:
```
<meta name="application-name" content="package-name">
<meta name="apple-mobile-web-app-title" content="package-name">
```

I'm assuming it is reading package.json `name` because I get that printed into the metas if not title is specified.
But in a react application a common scenario is to set that up with `react-helmet` dynamically: the problem is that when adding the website to home (to have a quick webapp launcher) safari detects that hard-coded meta and use that one instead of the dynamically written one (into the source page).
How can I disable favicons-webpack-plugin from writing that meta?

My current configuration:
```
            new FaviconsPlugin({
                // title: pkg.name,
                logo: pkg.logo,
                prefix: 'build/icons/',
                statsFilename: 'build/icons/stats.json',
                inject: true,
                emitStats: true,
                persistentCache: true,
            }),
```

**Comment by damianobarbati** [comment]
@jantimon it's actually injection a lots other info like `<meta name="apple-mobile-web-app-status-bar-style" content="black">`.
That's great but is there any way add configuration for them or disable them? 😅

**Comment by damianobarbati** [comment]
Abandoned repo? 😔

**Comment by Pushplaybang** [comment]
Seems that way, which is disappointing as this is really one of those tasks you want automated.....

**Comment by jantimon** [comment]
Resolved with 1.x
