### ISSUE TITLE
twitter and opengraph

### ISSUE THREAD

**Issue by AdamBarnwell** [jantimon/favicons-webpack-plugin#103]
Hi,
I'm slightly confused as I've set twitter and opengraph to true in the icons object but I'm not getting any images generated or the relevant HTML generated. I did some investigation and found that the favicons package actually doesn't support opengraph or twitter options for icons so I'm wondering why this is in your documentation as a supported icon type?

**Comment by JamesJefferyUK** [comment]
Exactly the same problem here too.

**Comment by iki** [comment]
+1, no such output icons seem to be supported by https://github.com/evilebottnawi/favicons#usage

**Comment by jantimon** [comment]
This sounds rather like an issue with https://github.com/itgalaxy/favicons (the library used by this plugin)

**Comment by Mouvedia** [comment]
https://github.com/itgalaxy/favicons/commit/7f59a2e20c1ed95605df07f496f484c4368de72e#diff-0730bb7c2e8f9ea2438b52e419dd86c9
