### ISSUE TITLE
<link>s not getting embedded with HtmlWebpackPlugin

### ISSUE THREAD

**Issue by mezod** [jantimon/favicons-webpack-plugin#104]
Hello,
I know this is not the right place to ask but I'm out of ideas. I'm using webpack 1.12.

I can see webpack is generating the files: https://imgur.com/a/qdMqO

But I cannot see any new <link>s on the <head>. I am also using HtmlWebpackPlugin. This is my initial try: 

Relevant part of the webpack cfg:
```
[
  new webpack.HotModuleReplacementPlugin(),
  new HtmlwebpackPlugin({
    title: 'everydayCheck',
    template: 'index.html',
    favicon: './app/images/everydaycheck.ico',
  }),
  new webpack.DefinePlugin({
    'process.env': {
      NODE_ENV: JSON.stringify('production'),
    },
  }),
  new webpack.optimize.UglifyJsPlugin({
    compress: {
      warnings: false,
    },
  }),
  new FaviconsWebpackPlugin('./app/images/logo.png'),
]
```

I've also tried removing the favicon from HtmlWebpackPlugin and also specifying inject to true:

```
  new FaviconsWebpackPlugin({
    logo: './app/images/logo.png',
    inject: true,
  }),
```

I obviously try to add to homescreen from the phone and it doesn't work...

Have you got any ideas or even ideas on how to debug this?

Thank you :)

**Comment by thisguychris** [comment]
hey @mezod where you able to make it work, running to a similar issue

**Comment by mezod** [comment]
Hey @thisguychris been investigating here to try to remember what I did to make it work and I sadly don't remember. I see that I'm using this library exactly as in the config above and it does generate the links properly. My last bit of the webpack config looks like:

```
  output: {
    path: PROD ? path.resolve(ROOT_PATH, 'dist') :
      path.resolve(ROOT_PATH, 'app/build'),
    publicPath: '/',
    filename: 'bundle.js',
  },
  devServer: {
    contentBase: path.resolve(ROOT_PATH, 'dist'),
    historyApiFallback: true,
    hot: true,
    inline: true,
    progress: true,
  },
  plugins,
};
```

but I can't remember if it has any relation to this... I'm sorry can't recall what the heck I did to make it work!
