### ISSUE TITLE
Non-deterministic builds from files order

### ISSUE THREAD

**Issue by wbobeirne** [jantimon/favicons-webpack-plugin#105]
I have a build where determinism is important because we hash the zipped output, and make sure that the hash is the same across multiple environments. We've found that both the `.cache` and the html output is sometimes different because the order of files can be different. It would be ideal if this were always the same. I think it could be as simple as sorting `result.html`, `result.files`, and `result.images` before using them in [this callback function](https://github.com/jantimon/favicons-webpack-plugin/blob/master/lib/favicons.js#L55) but I wanted to check in before submitting a PR of my own.

Let me know if I'm wrong about that, or if this doesn't seem correct!

**Comment by jantimon** [comment]
Should be solved in favicons-webpack-plugin 1.0.0 by #157 can you please give it a try?
