### ISSUE TITLE
Maintaining this project

### ISSUE THREAD

**Issue by ciampo** [jantimon/favicons-webpack-plugin#106]
Hi @jantimon ,

first of all I wanted to thank you for having coded a few very useful Webpack plugins in the past years.

I appreciate that this project is open source software and that most probably you developed it during your free time. At the same time, this project is quite a popular one (15k+ downloads/week, 500+ github stars), and I bet a few projects rely on it. I noticed that you haven't been working at it in the past 7 months, and that you mostly ignored the issues and the PRs that people have opened.

My question is: do you still have the time to maintain and develop this project? If you don't, it would be a pity to just abandon what you've built—I'm sure that there would be a few people happy to help developing this repo further.

**Comment by brunocodutra** [comment]
According to the discussion in #92 it looks like there are plans for a new release

**Comment by jantimon** [comment]
Hey - like you see in #92 we tried to get movement into this issue and also got support by https://github.com/evilebottnawi/favicons to introduce new features.

The favicon topic introduces a lot of work and I would happy to move this project further but I don't have the time to do it alone. Would be happy to get some support - especially now that webpack 4 is released and the https://github.com/webpack/tapable was changed

**Comment by jantimon** [comment]
Would love to merge that back into this project
