### ISSUE TITLE
Webpack 4 compat

### ISSUE THREAD

**Issue by dweber019** [jantimon/favicons-webpack-plugin#108]
Please update the plugin to work with webpack 4.
Thx

**Comment by hlehmann** [comment]
This is the error I get:

```
Error: Plugin could not be registered at 'html-webpack-plugin-before-html-processing'. Hook was not found.
BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compatiblity layer for this hook, hook into 'this._pluginCompat'.
    at Compilation.plugin (node_modules/tapable/lib/Tapable.js:63:9)
    at Compilation.deprecated [as plugin] (internal/util.js:53:15)
    at node_modules/favicons-webpack-plugin/index.js:57:19
```

**Comment by gorbypark** [comment]
I get this error with webpack 4:
```✖ ｢wdm｣: Error: Module build failed: TypeError: Cannot read property 'context' of undefined```

**Comment by brunocodutra** [comment]
Meanwhile you could try [webapp-webpack-plugin](https://www.npmjs.com/package/webapp-webpack-plugin) which I originally forked from favicons-webpack-plugin to add some missing functionality, including support for Webpack 4.

**Comment by jantimon** [comment]
Released 0.0.8

**Comment by skizzo** [comment]
Still not working.

**Comment by Chanaeva** [comment]
Doesn't seem to be working?   Error: Module build failed (from ./node_modules/favicons-webpack-plugin/lib/favicons.js):
