### ISSUE TITLE
Optimize Images

### ISSUE THREAD

**Issue by Klathmon** [jantimon/favicons-webpack-plugin#11]
I noticed that image-webpack-loader doesn't touch the files this plugin produces, is there any way to optimize them to compress them a bit?

**Comment by jantimon** [comment]
Unfortunately the image-webpack-loader doesn't support this by now.
We would have to extract the minification of the image-webpack-loader into a separate function / file so it could be called with the streams of the favicon output.
You could also ask the favicon project to support image optimizations.

**Comment by Klathmon** [comment]
So this was bothering me more than I care to admit, so I created a plugin ([`imagemin-webpack-plugin`](https://github.com/Klathmon/imagemin-webpack-plugin)) that will minify all images in a webpack project, including images from this library. Just figured I'd throw it out there in case anyone else stumbles upon this and wants a solution.
