### ISSUE TITLE
Deprecation warning on compilation

### ISSUE THREAD

**Issue by bvarga256** [jantimon/favicons-webpack-plugin#112]
During compilation, two deprecation warning is triggered (version 0.0.8, OS Windows, Webpack 4.3.0, WDS 3.1.1).

(node:7048) **DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead**
    at FaviconsWebpackPlugin.apply (c:\wamp64\www\node_modules\favicons-webpack-plugin\index.js:44:12)
    at webpack (c:\wamp64\www\node_modules\webpack\lib\webpack.js:37:12)
    at [...]

(node:7048) **DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead**
    at Object.compileTemplate (c:\wamp64\www\node_modules\favicons-webpack-plugin\lib\compiler.js:18:17)
    at c:\wamp64\www\node_modules\favicons-webpack-plugin\index.js:45:19
    at [...]

p.s.: Thank you for this awesome plugin.

**Comment by chrispickford** [comment]
I'm getting the same warnings in version `0.0.8`. I can see in `index.js` that Webpack 4 support has been added but it seems there are additional legacy references to tapable that have been missed.

> DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at FaviconsWebpackPlugin.apply (~\node_modules\favicons-webpack-plugin\index.js:44:12)
``` javascript
// Generate the favicons
var compilationResult;
compiler.plugin('make', function (compilation, callback) {  ///////////////////// DEPRECATED CALL
  childCompiler.compileTemplate(self.options, compiler.context, compilation)
    .then(function (result) {
      compilationResult = result;
      callback();
    })
    .catch(callback);
});
```
> DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
    at Object.compileTemplate (~\node_modules\favicons-webpack-plugin\lib\compiler.js:18:17)
``` javascript
// Create an additional child compiler which takes the template
// and turns it into an Node.JS html factory.
// This allows us to use loaders during the compilation
var compilerName = getCompilerName(context, outputOptions.filename);
var childCompiler = compilation.createChildCompiler(compilerName, outputOptions);
childCompiler.context = context;
childCompiler.apply( //////////////////////////////////////////////////////////// DEPRECATED CALL
  new SingleEntryPlugin(context, '!!' + require.resolve('./favicons.js') + '?' +
    JSON.stringify({
      outputFilePrefix: options.prefix,
      icons: options.icons,
      background: options.background,
      persistentCache: options.persistentCache,
      appName: options.title
    }) + '!' + options.logo)
);
```

**Comment by romanlex** [comment]
webpack v4 support forked plugin https://github.com/romanlex/app-manifest-webpack-plugin

**Comment by bvarga256** [comment]
I'm closing this issue, because version 0.0.9 fixes this issue. Thank you!

**Comment by m-adil** [comment]
I'm using 0.0.9 but still got the erorr:
```
(node:78739) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
TypeError: Cannot read property 'tapAsync' of undefined
```
