### ISSUE TITLE
No option for short_name in manifest.json

### ISSUE THREAD

**Issue by jesperlehtinen** [jantimon/favicons-webpack-plugin#116]
There seems to be no option for manifest.json property `short_name`. Currently it takes the `title` property from plugin config and sets as `short_name`, which risks be truncated if it's > 12 characters.

**Comment by romanlex** [comment]
@jesperlehtinen you can use https://github.com/romanlex/app-manifest-webpack-plugin

**Comment by jesperlehtinen** [comment]
@romanlex I can't see that your fork has any options for short_name either?

**Comment by romanlex** [comment]
@jesperlehtinen oh...sry
You can create issues in https://github.com/evilebottnawi/favicons for add support `short_name` property and use my fork for this. My fork support all properties from `favicons` package

**Comment by jesperlehtinen** [comment]
@romanlex thanks I'll open an issue and maybe submit a PR there.
