### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by tremby** [jantimon/favicons-webpack-plugin#117]
Would it be possible to add support for SVG source images?

**Comment by omieliekh** [comment]
It is supported at the moment. Just don't forget to set `viewBox` in your svg.
I've just set both width/height and viewBox and it worked
```svg
<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 100 100">
    ...
</svg>

```

**Comment by tremby** [comment]
OK, I'll give it another go... I had blank images out before. May have been missing the viewbox.

**Comment by tremby** [comment]
That did the trick. Might be worth mentioning in the readme that it's a requirement? I would have thought it'd make a default viewbox based on width and height (`0 0 width height`) -- that's what browsers seem to do after all.
