### ISSUE TITLE
Enormous memory usage

### ISSUE THREAD

**Issue by tremby** [jantimon/favicons-webpack-plugin#118]
Adding this package took the memory usage of my build operation from comfortable to enough to crash the build server. This build server has 8G of RAM and is otherwise idle.

Incidentally, why in the world is there a dependency on phantomjs just to resize some images?

Edit: I look closer and see that phantomjs is a dependency of svg2png, which is a dependency of favicons. I'm not passing an SVG so I shouldn't think phantom is being used. (I didn't think this supported SVGs hence my other ticket -- I got blank output images when I tried using one.)

So why am I getting such huge memory usage? I thought giving a large image as input would be wise, since one of the outputs is ~1500 pixels wide. The one I'm passing in is a 2000x2000 PNG.

**Comment by tremby** [comment]
I now strongly suspect it was just during installation (and compilation) of phantomjs.

**Comment by wouterds** [comment]
I "fixed" my circle ci builds and basically all my problems by resizing my source image from `2048x2048` to `1024x1024` 🙈...

**Comment by jantimon** [comment]
Done in #157.

Can you please take a look?

**Comment by tremby** [comment]
I'm stepping out, since I'm not doing anything where I need this package right now (16 months later). I'd at least review the changeset to see what you've done, but what you've pointed to is an enormous merge and it's not clear which commits are relevant to this particular issue. Perhaps one of the other participants or upvoters can take over.
