### ISSUE TITLE
"file" argument must be a non-empty string

### ISSUE THREAD

**Issue by djeeg** [jantimon/favicons-webpack-plugin#120]
Previously was using a png to create icons and had no issues.

Have now swapped to use a svg and am getting this error.

```
            new FaviconsWebpackPlugin({
                logo: path.resolve(__dirname, "../../..", "src/images/logo.svg"),
```

**Comment by djeeg** [comment]
Okay I think this is coming from here:

https://github.com/evilebottnawi/favicons/blob/c08ff71fef915ef7c75ea3b1c63f61c4cf33dd6a/src/helpers.js#L233

**Comment by jacobpdq** [comment]
Christ. Thanks for this, big help
