### ISSUE TITLE
The site verification tool gives warnings

### ISSUE THREAD

**Issue by VadyaVL** [jantimon/favicons-webpack-plugin#123]
Good day.
Checking the site with one tool gets a lot of warning.
Can I specify specific sizes and number of generated favicons.

The service recommends using one of the largest icons.

`line 8  col 5    Warning  A 'apple-touch-icon' was already specifi apple-touch-icons`
`line 8  col 122  Warning  A 'apple-touch-icon' was already specifi apple-touch-icons`
`line 8  col 239  Warning  A 'apple-touch-icon' was already specifi apple-touch-icons`
`line 8  col 356  Warning  A 'apple-touch-icon' was already specifi apple-touch-icons`
`line 8  col 473  Warning  A 'apple-touch-icon' was already specifi apple-touch-icons`
`line 8  col 594  Warning  A 'apple-touch-icon' was already specifi apple-touch-icons`
`line 8  col 715  Warning  A 'apple-touch-icon' was already specifi apple-touch-icons`
`line 8  col 836  Warning  A 'apple-touch-icon' was already specifi apple-touch-icons`
`line 8  col 957  Warning  'sizes' attribute is not needed apple-touch-icons`

**I have:**
`<link rel="apple-touch-icon" sizes="57x57" href="icons-366a3768de05f9e78c392fa62b8fbb80/apple-touch-icon-57x57.png">`
`<link rel="apple-touch-icon" sizes="60x60" href="icons-366a3768de05f9e78c392fa62b8fbb80/apple-touch-icon-60x60.png">`
`<link rel="apple-touch-icon" sizes="72x72" href="icons-366a3768de05f9e78c392fa62b8fbb80/apple-touch-icon-72x72.png">`

**I need only:**
`<link rel="apple-touch-icon" href="icons-366a3768de05f9e78c392fa62b8fbb80/apple-touch-icon-180x180.png">`

_It would be nice to be able to point out some restrictions for generating._

Thank you for attention.

**Comment by jantimon** [comment]
That would be something for the library behind this plugin: https://github.com/itgalaxy/favicons
