### ISSUE TITLE
NSP Security Check Fails

### ISSUE THREAD

**Issue by noqcks** [jantimon/favicons-webpack-plugin#125]
Im using https://github.com/nodesecurity/nsp to scan for vulnerable dependencies.

```
➜  nsp check --reporter summary

(+) 1 vulnerabilities found
 Name     Installed   Patched                        Path                                                                                    More Info
 debug    2.2.0       >= 2.6.9 < 3.0.0 || >= 3.1.0   favicons-webpack-plugin@0.0.9 > favicons@4.8.6 > node-rest-client@1.8.0 > debug@2.2.0   https://nodesecurity.io/advisories/534
```
Link: https://nodesecurity.io/advisories/534

It looks like debug was updated in favicons > 5.0.0.

**Comment by jantimon** [comment]
I might be wrong but the security issue does not affect the usage here - you are not able to pass regular expressions to debug

**Comment by noqcks** [comment]
Perfect! Thank you for addressing. I'll close this issue then. It's a very small security issues regardless, just wanted to make you aware of it.
