### ISSUE TITLE
Feature request: disable prefix

### ISSUE THREAD

**Issue by Eterion** [jantimon/favicons-webpack-plugin#128]
Hi, I was wondering if it would be possible to disable the prefix on favicons files when prefix is set to `false`.

Sure, the use of prefix is fine when you're using pretty much default webpack build, however you run into minor problems/annoyances the moment you use custom templates or just want plain old static favicons generated or when you want the favicons in output root.

It would be nice to have `prefix: false`, in which case the prefix would just be completely disabled. Right now I can do something similar with `prefix: '/'`, but this adds the forward slash to the icon path where I just don't want it.

**Comment by ajbrun** [comment]
Added pull request: #134 

In addition, it's recommended that favicons are generated into the root. Some browsers don't look at where they're referenced as you'd expect.
https://realfavicongenerator.net/faq#why_icons_in_root

**Comment by nstuyvesant** [comment]
As a workaround, I set `prefix: './' `to prevent the hashes from being generated and drop it into the base directory. As I also set `inject: true`, the injections look like this:
` <link rel="icon" type="image/png" sizes="32x32" href="/./favicon-32x32.png">`
Ugly, but they work.

I would rather set prefix to '' or false to avoid the hashes and stick everything in the base directory.

**Comment by jantimon** [comment]
You can set prefix to: ''

**Comment by binarykitchen** [comment]
@jantimon no, setting prefix to `` is breaking. It results into a 404 when in root of webpack's publicPath
