### ISSUE TITLE
Plugin throws w/o html-webpack-plugin in place

### ISSUE THREAD

**Issue by djfarly** [jantimon/favicons-webpack-plugin#130]
I don't really know why it actually even enters said hook, since html-webpack-plugin is nowhere in my webpack configuration. PR incoming.

<img width="724" alt="bildschirmfoto 2018-06-03 um 20 26 30" src="https://user-images.githubusercontent.com/5230863/40889750-73ed4744-676c-11e8-8e4c-d69308784b8c.png">

**Comment by jantimon** [comment]
Done in #157.

Can you please take a look?
