### ISSUE TITLE
ejs injection

### ISSUE THREAD

**Issue by landru29** [jantimon/favicons-webpack-plugin#133]
Is it possible to set `inject: false` and manually inject data in ejs file via an available variable ?
I tried 
```
<pre><%= JSON.stringify(faviconsWebpackPlugin, null, 4) %></pre>
```
but it did not worked

For your information the fillowing work:
```
<% for (var i=0; i<htmlWebpackPlugin.files.js.length; i++) { %>
            <script src="<%= htmlWebpackPlugin.files.js[i].path %>"></script>
        <% } %>
```

**Comment by hypernova7** [comment]
i like that option

**Comment by jantimon** [comment]
With html-webpack-plugin 4.x and the upcoming favicons-webpack-plugin 3.x #184 this will be possible.

Even if you set `inject:false` for html-webpack-plugin the favicons webpack plugin will provide the information to the ejs file.

**Comment by jantimon** [comment]
Here is an [example](https://github.com/jantimon/favicons-webpack-plugin/tree/master/example/no-inject) which is using 

- [html-webpack-plugin 4.x](https://www.npmjs.com/package/html-webpack-plugin/v/4.0.0-beta.11)
- favicons-webpack-plugin 3.x

https://github.com/jantimon/favicons-webpack-plugin/tree/master/example/no-inject

Your `<head>` might look like this:

https://github.com/jantimon/favicons-webpack-plugin/blob/47bf751d3e9c945c77fbd853d46c8ce70d08b338/example/no-inject/src/index.html#L4-L10
