### ISSUE TITLE
using with html-webpack-plugin

### ISSUE THREAD

**Issue by yrtimiD** [jantimon/favicons-webpack-plugin#14]
In readme you did mention that this plugin can work with html-webpack-plugin to inject all generated icons, unfortunately I can't make it work and can't find any example of how html-webpack-plugin configuration should look to work together. 
Can you provide an example of minimal webpack.config.js?

**Comment by jantimon** [comment]
Just add both modules and you are done:

https://github.com/jantimon/favicons-webpack-plugin/blob/master/test/index.js#L97-L104

**Comment by alexdrans** [comment]
Hi @jantimon, I'm having this same issue; the favicons are being generated but they are not automatically being added to my page through html-webpack-plugin. Here's the relevant section of my webpack.config.js;

`new FaviconsWebpackPlugin({
      logo: './newicon.png',
      persistentCache: true
    }),
    new HtmlWebpackPlugin({
      filename: 'index.html',
      title: 'title',
      template: 'src/index.html',
      minify: {
        collapseWhitespace: false,
        removeComments: false,
        removeRedundantAttributes: false,
        removeScriptTypeAttributes: false,
        removeStyleLinkTypeAttributes: false
      }
    }),
    new HtmlWebpackPlugin({
      filename: 'home.html',
      title: 'title',
      template: 'src/homepage/home.html',
      minify: {
        collapseWhitespace: true,
        removeComments: true,
        removeRedundantAttributes: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true
      }`

Is there anything obviously wrong here..? I'm stumped.

**Comment by jantimon** [comment]
Hmm could you add some console.log messages here?

https://github.com/jantimon/favicons-webpack-plugin/blob/master/index.js#L55-L64

And try to give me a hint why this might happen?

**Comment by alexdrans** [comment]
Thanks for the quick reply @jantimon!

I added logs in these places;

`if (self.options.inject) {
    console.log('self.options.inject', self.options.inject);
    compiler.plugin('compilation', function (compilation) {
      console.log('compilation', compilation);
      compilation.plugin('html-webpack-plugin-before-html-processing', function (htmlPluginData, callback) {
        console.log('htmlPluginData', htmlPluginData);
        if (htmlPluginData.plugin.options.favicons !== false) {
          console.log(compilationResult);
          htmlPluginData.html = htmlPluginData.html.replace(
            /(<\/head>)/i, compilationResult.stats.html.join('') + '$&');
          callback(null, htmlPluginData);
        }
      });
    });
  }`

which produced;

`self.options.inject true
compilation Compilation {
  _plugins:
   { 'normal-module-loader': [ [Function] ],
     optimize: [ [Function] ],
     'optimize-tree': [ [Function: bound ] ],
     'additional-assets': [ [Function: bound ] ] },
  compiler:
   Compiler {
     _plugins:
      { compilation: [Object],
        'this-compilation': [Object],
        make: [Object],
        emit: [Object],
        done: [Object],
        'after-resolvers': [Object],
        'entry-option': [Object],
        'context-module-factory': [Object],
        run: [Object],
        'after-compile': [Object],
        compile: [Object],
        invalid: [Object],
        'watch-run': [Object] },
     outputPath: '/',
     outputFileSystem: MemoryFileSystem { data: {} },
     inputFileSystem:
      CachedInputFileSystem {
        fileSystem: NodeJsInputFileSystem {},
        _statStorage: [Object],
        _readdirStorage: [Object],
        _readFileStorage: [Object],
        _readlinkStorage: [Object] },
     recordsInputPath: undefined,
     recordsOutputPath: undefined,
     records: {},
     fileTimestamps: {},
     contextTimestamps: {},
     resolvers: { normal: [Object], loader: [Object], context: [Object] },
     parser: Parser { _plugins: [Object], options: undefined },
     options:
      { entry: [Object],
        output: [Object],
        plugins: [Object],
        module: [Object],
        devtool: 'source-map',
        context: '/Users/alexdransfield/Code/webapp',
        debug: false,
        cache: true,
        target: 'web',
        node: [Object],
        resolve: [Object],
        resolveLoader: [Object],
        optimize: [Object] },
     context: '/Users/alexdransfield/Code/webapp',
     name: undefined,
     _currentPluginApply: 2,
     watchFileSystem:
      NodeWatchFileSystem {
        inputFileSystem: [Object],
        watcherOptions: [Object],
        watcher: [Object] } },
  resolvers:
   { normal:
      Tapable {
        _plugins: [Object],
        fileSystem: [Object],
        resolve: [Function: resolve] },
     loader:
      Tapable {
        _plugins: [Object],
        fileSystem: [Object],
        resolve: [Function: resolve] },
     context:
      Tapable {
        _plugins: [Object],
        fileSystem: [Object],
        resolve: [Function: resolve] } },
  inputFileSystem:
   CachedInputFileSystem {
     fileSystem: NodeJsInputFileSystem {},
     _statStorage:
      Storage {
        duration: 60000,
        running: {},
        data: {},
        levels: [Object],
        count: 0,
        interval: null,
        needTickCheck: false,
        nextTick: null,
        passive: true },
     _readdirStorage:
      Storage {
        duration: 60000,
        running: {},
        data: {},
        levels: [Object],
        count: 0,
        interval: null,
        needTickCheck: false,
        nextTick: null,
        passive: true },
     _readFileStorage:
      Storage {
        duration: 60000,
        running: {},
        data: {},
        levels: [Object],
        count: 0,
        interval: null,
        needTickCheck: false,
        nextTick: null,
        passive: true },
     _readlinkStorage:
      Storage {
        duration: 60000,
        running: {},
        data: {},
        levels: [Object],
        count: 0,
        interval: null,
        needTickCheck: false,
        nextTick: null,
        passive: true } },
  options:
   { entry: { app: [Object], home: [Object] },
     output:
      { path: '/',
        filename: '[name].js',
        libraryTarget: 'var',
        sourceMapFilename: '[file].map[query]',
        hotUpdateChunkFilename: '[id].[hash].hot-update.js',
        hotUpdateMainFilename: '[hash].hot-update.json',
        crossOriginLoading: false,
        hashFunction: 'md5',
        hashDigest: 'hex',
        hashDigestLength: 20,
        sourcePrefix: '\t',
        devtoolLineToLine: false },
     plugins:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     module:
      { loaders: [Object],
        unknownContextRequest: '.',
        unknownContextRecursive: true,
        unknownContextRegExp: /^\.\/.*$/,
        unknownContextCritical: true,
        exprContextRequest: '.',
        exprContextRegExp: /^\.\/.*$/,
        exprContextRecursive: true,
        exprContextCritical: true,
        wrappedContextRegExp: /.*/,
        wrappedContextRecursive: true,
        wrappedContextCritical: false },
     devtool: 'source-map',
     context: '/Users/alexdransfield/Code/webapp',
     debug: false,
     cache: true,
     target: 'web',
     node:
      { console: false,
        process: true,
        global: true,
        setImmediate: true,
        __filename: 'mock',
        __dirname: 'mock' },
     resolve:
      { fastUnsafe: [],
        alias: {},
        packageAlias: 'browser',
        modulesDirectories: [Object],
        packageMains: [Object],
        extensions: [Object] },
     resolveLoader:
      { fastUnsafe: [],
        alias: {},
        modulesDirectories: [Object],
        packageMains: [Object],
        extensions: [Object],
        moduleTemplates: [Object] },
     optimize: { occurenceOrderPreferEntry: true } },
  outputOptions:
   { path: '/',
     filename: '[name].js',
     libraryTarget: 'var',
     sourceMapFilename: '[file].map[query]',
     hotUpdateChunkFilename: '[id].[hash].hot-update.js',
     hotUpdateMainFilename: '[hash].hot-update.json',
     crossOriginLoading: false,
     hashFunction: 'md5',
     hashDigest: 'hex',
     hashDigestLength: 20,
     sourcePrefix: '\t',
     devtoolLineToLine: false },
  bail: undefined,
  profile: undefined,
  mainTemplate:
   Template {
     _plugins:
      { startup: [Object],
        render: [Object],
        'local-vars': [Object],
        require: [Object],
        'module-obj': [Object],
        'require-extensions': [Object],
        'jsonp-script': [Object],
        'require-ensure': [Object],
        bootstrap: [Object],
        'hot-bootstrap': [Object],
        hash: [Object] },
     outputOptions:
      { path: '/',
        filename: '[name].js',
        libraryTarget: 'var',
        sourceMapFilename: '[file].map[query]',
        hotUpdateChunkFilename: '[id].[hash].hot-update.js',
        hotUpdateMainFilename: '[hash].hot-update.json',
        crossOriginLoading: false,
        hashFunction: 'md5',
        hashDigest: 'hex',
        hashDigestLength: 20,
        sourcePrefix: '\t',
        devtoolLineToLine: false } },
  chunkTemplate:
   Template {
     _plugins: { render: [Object], hash: [Object] },
     outputOptions:
      { path: '/',
        filename: '[name].js',
        libraryTarget: 'var',
        sourceMapFilename: '[file].map[query]',
        hotUpdateChunkFilename: '[id].[hash].hot-update.js',
        hotUpdateMainFilename: '[hash].hot-update.json',
        crossOriginLoading: false,
        hashFunction: 'md5',
        hashDigest: 'hex',
        hashDigestLength: 20,
        sourcePrefix: '\t',
        devtoolLineToLine: false } },
  hotUpdateChunkTemplate:
   Template {
     _plugins: { render: [Object], hash: [Object] },
     outputOptions:
      { path: '/',
        filename: '[name].js',
        libraryTarget: 'var',
        sourceMapFilename: '[file].map[query]',
        hotUpdateChunkFilename: '[id].[hash].hot-update.js',
        hotUpdateMainFilename: '[hash].hot-update.json',
        crossOriginLoading: false,
        hashFunction: 'md5',
        hashDigest: 'hex',
        hashDigestLength: 20,
        sourcePrefix: '\t',
        devtoolLineToLine: false } },
  moduleTemplate:
   Template {
     _plugins: {},
     outputOptions:
      { path: '/',
        filename: '[name].js',
        libraryTarget: 'var',
        sourceMapFilename: '[file].map[query]',
        hotUpdateChunkFilename: '[id].[hash].hot-update.js',
        hotUpdateMainFilename: '[hash].hot-update.json',
        crossOriginLoading: false,
        hashFunction: 'md5',
        hashDigest: 'hex',
        hashDigestLength: 20,
        sourcePrefix: '\t',
        devtoolLineToLine: false } },
  entries: [],
  preparedChunks: [],
  chunks: [],
  namedChunks: {},
  modules: [],
  _modules: {},
  cache: null,
  records: {},
  nextFreeModuleId: 1,
  nextFreeChunkId: 0,
  nextFreeModuleIndex: 0,
  nextFreeModuleIndex2: 0,
  additionalChunkAssets: [],
  assets: {},
  errors: [],
  warnings: [],
  children: [],
  dependencyFactories: ArrayMap { keys: [ [Object] ], values: [ NullFactory {} ] },
  dependencyTemplates: ArrayMap { keys: [ [Object] ], values: [ ConstDependencyTemplate {} ] },
  fileTimestamps: {},
  contextTimestamps: {},
  name: undefined }
  0% compilecompilation Compilation {
  _plugins: {},
  compiler:
   Compiler {
     _plugins:
      { compilation: [Object],
        'after-resolvers': [Object],
        'entry-option': [Object],
        'context-module-factory': [Object],
        run: [Object],
        'after-compile': [Object],
        'watch-run': [Object],
        make: [Object] },
     outputPath: '/',
     outputFileSystem: null,
     inputFileSystem:
      CachedInputFileSystem {
        fileSystem: NodeJsInputFileSystem {},
        _statStorage: [Object],
        _readdirStorage: [Object],
        _readFileStorage: [Object],
        _readlinkStorage: [Object] },
     recordsInputPath: null,
     recordsOutputPath: null,
     records: {},
     fileTimestamps: {},
     contextTimestamps: {},
     resolvers: { normal: [Object], loader: [Object], context: [Object] },
     parser: Parser { _plugins: [Object], options: undefined },
     options: { output: [Object] },
     name: 'favicons-webpack-plugin for "iconstats-[hash].json"',
     parentCompilation:
      Compilation {
        _plugins: [Object],
        compiler: [Object],
        resolvers: [Object],
        inputFileSystem: [Object],
        options: [Object],
        outputOptions: [Object],
        bail: undefined,
        profile: undefined,
        mainTemplate: [Object],
        chunkTemplate: [Object],
        hotUpdateChunkTemplate: [Object],
        moduleTemplate: [Object],
        entries: [],
        preparedChunks: [],
        chunks: [],
        namedChunks: {},
        modules: [],
        _modules: {},
        cache: {},
        records: [Object],
        nextFreeModuleId: 1,
        nextFreeChunkId: 0,
        nextFreeModuleIndex: 0,
        nextFreeModuleIndex2: 0,
        additionalChunkAssets: [],
        assets: {},
        errors: [],
        warnings: [],
        children: [],
        dependencyFactories: [Object],
        dependencyTemplates: [Object],
        fileTimestamps: {},
        contextTimestamps: {},
        name: undefined },
     context: '/Users/alexdransfield/Code/webapp',
     _currentPluginApply: 2 },
  resolvers:
   { normal:
      Tapable {
        _plugins: [Object],
        fileSystem: [Object],
        resolve: [Function: resolve] },
     loader:
      Tapable {
        _plugins: [Object],
        fileSystem: [Object],
        resolve: [Function: resolve] },
     context:
      Tapable {
        _plugins: [Object],
        fileSystem: [Object],
        resolve: [Function: resolve] } },
  inputFileSystem:
   CachedInputFileSystem {
     fileSystem: NodeJsInputFileSystem {},
     _statStorage:
      Storage {
        duration: 60000,
        running: {},
        data: {},
        levels: [Object],
        count: 0,
        interval: null,
        needTickCheck: false,
        nextTick: null,
        passive: true },
     _readdirStorage:
      Storage {
        duration: 60000,
        running: {},
        data: {},
        levels: [Object],
        count: 0,
        interval: null,
        needTickCheck: false,
        nextTick: null,
        passive: true },
     _readFileStorage:
      Storage {
        duration: 60000,
        running: {},
        data: {},
        levels: [Object],
        count: 0,
        interval: null,
        needTickCheck: false,
        nextTick: null,
        passive: true },
     _readlinkStorage:
      Storage {
        duration: 60000,
        running: {},
        data: {},
        levels: [Object],
        count: 0,
        interval: null,
        needTickCheck: false,
        nextTick: null,
        passive: true } },
  options: { output: { filename: 'iconstats-[hash].json', publicPath: undefined } },
  outputOptions: { filename: 'iconstats-[hash].json', publicPath: undefined },
  bail: undefined,
  profile: undefined,
  mainTemplate:
   Template {
     _plugins:
      { startup: [Object],
        render: [Object],
        'local-vars': [Object],
        require: [Object],
        'module-obj': [Object],
        'require-extensions': [Object] },
     outputOptions: { filename: 'iconstats-[hash].json', publicPath: undefined } },
  chunkTemplate:
   Template {
     _plugins: {},
     outputOptions: { filename: 'iconstats-[hash].json', publicPath: undefined } },
  hotUpdateChunkTemplate:
   Template {
     _plugins: {},
     outputOptions: { filename: 'iconstats-[hash].json', publicPath: undefined } },
  moduleTemplate:
   Template {
     _plugins: {},
     outputOptions: { filename: 'iconstats-[hash].json', publicPath: undefined } },
  entries: [],
  preparedChunks: [],
  chunks: [],
  namedChunks: {},
  modules: [],
  _modules: {},
  cache: null,
  records: {},
  nextFreeModuleId: 1,
  nextFreeChunkId: 0,
  nextFreeModuleIndex: 0,
  nextFreeModuleIndex2: 0,
  additionalChunkAssets: [],
  assets: {},
  errors: [],
  warnings: [],
  children: [],
  dependencyFactories: ArrayMap { keys: [ [Object] ], values: [ NullFactory {} ] },
  dependencyTemplates: ArrayMap { keys: [ [Object] ], values: [ ConstDependencyTemplate {} ] },
  fileTimestamps: {},
  contextTimestamps: {},
  name: 'favicons-webpack-plugin for "iconstats-[hash].json"' }`

**Comment by alexdrans** [comment]
It appears that this line isn't hitting the callback;

`compilation.plugin('html-webpack-plugin-before-html-processing', function (htmlPluginData, callback) {`

**Comment by jantimon** [comment]
Which html-webpack-plugin version do you use?

**Comment by alexdrans** [comment]
1.7.0

**Comment by jantimon** [comment]
Oh - `html-webpack-plugin-before-html-processing` was introduced 1 month ago and 1.7 was released Nov 23, 2015..

**Comment by alexdrans** [comment]
Working! Thanks for being patient. Should I PR README.md to warn others of this?

**Comment by jantimon** [comment]
Yeah that would be nice 👍

**Comment by casoetan** [comment]
So whats the solution please?

**Comment by alexdrans** [comment]
Make sure you're on the latest version of ``favicons-webpack-plugin``!

**Comment by casoetan** [comment]
I am, but its building and generating the icons, but its not injecting it into the html template

**Comment by alexdrans** [comment]
Can you post your ``webpack.config.js``?

**Comment by casoetan** [comment]
```js
const { resolve } = require('path')
const webpack = require('webpack')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const ExtractTextPlugin = require('extract-text-webpack-plugin')

const FaviconsWebpackPlugin = require('favicons-webpack-plugin')

module.exports = env => ({
  devtool: env.prod ? 'source-map' : 'eval',
  context: resolve(__dirname, './src'),
  entry: {
    app: [
      'react-hot-loader/patch',
      './index.js',
      './index.scss'
    ]
  },
  output: {
    path: resolve(__dirname, './dist'),
    filename: '[name].[chunkhash].bundle.js',
    sourceMapFilename: '[name].[chunkhash].bundle.map',
    chunkFilename: '[id].[chunkhash].chunk.js',
    pathinfo: !env.prod
  },
  devServer: {
    contentBase: './src',
    hot: true
  },
  bail: env.prod,
  module: {
    rules: [
      {
        enforce: 'pre',
        test: /\.(js|jsx)$/,
        loader: 'standard',
        exclude: /node_modules/
      },
      {
        test: /\.(js|jsx)$/,
        loader: 'babel!eslint',
        exclude: /node_modules/
      },
      {
        // enforce: 'pre',
        test: /\.(scss|sass)$/,
        exclude: [/node_modules/],
        loader: ExtractTextPlugin.extract({
          fallbackLoader: 'style',
          loader: 'css!postcss!sass'
        })
      },
      {
        test: /\.css$/,
        loaders: [
          'style-loader',
          'css-loader',
          'postcss-loader'
        ]
      },
    ]
  },
  resolve: {
    extensions: ['.js', '.jsx', '.scss', '.css']
  },
  plugins: [
    new webpack.optimize.UglifyJsPlugin({
      mangle: { screw_ie8 : true },
      compress: { screw_ie8: true }
    }),
    new ExtractTextPlugin({
      filename: '[name].[id].style.css',
      allChunks: true
    }),
    new HtmlWebpackPlugin({
      template: './index.html',
      title: 'BLW ISR APP',
      hash: true,
    }),
    new FaviconsWebpackPlugin({
      logo: './assets/images/blwisr.png',
      prefix: 'icons-[hash]/',
      emitStats: true,
      statsFilename: 'iconstats-[hash].json',
      persistentCache: true,
      inject: true,
      background: '#fff',
      title: 'BLWISR App',
      icons: {
        android: true,
        appleIcon: true,
        appleStartup: true,
        coast: false,
        favicons: true,
        firefox: true,
        opengraph: false,
        twitter: true,
        yandex: false,
        windows: false
      }
    }),
    new webpack.optimize.CommonsChunkPlugin({
      name: 'common',
      filename: 'bundle.common.js',
      minChunks: Infinity
    }),
    new webpack.LoaderOptionsPlugin({
      minimize: false,
      debug: true,
      options: {
        htmlLoader: {
          minimize: true,
          removeAttributeQuotes: false,
          caseSensitive: true
        }
      }
    })
  ],
})
```

**Comment by alexdrans** [comment]
Config looks fine to me. Works in my build. Can you just confirm the versions of ``favicons-webpack-plugin`` and ``html-webpack-plugin`` you have?

**Comment by alexdrans** [comment]
Try a simle config like ``new FaviconsWebpackPlugin('./assets/images/blwisr.png')``

**Comment by casoetan** [comment]
Same issue
<ode>"favicons-webpack-plugin": "^0.0.7"</code>

**Comment by alexdrans** [comment]
Easily done. Glad we figured it out!

**Comment by casoetan** [comment]
Still not working here?

**Comment by alexdrans** [comment]
``0.0.7`` and ``2.24.1`` are the respective latest versions of ``favicons-webpack-plugin`` and ``html-webpack-plugin``. Are the icons being generated?

**Comment by alexdrans** [comment]
If you're sure you're on the latest versions, all that I can recommend now is diving into the source and attempting to debug around [here](https://github.com/jantimon/favicons-webpack-plugin/blob/master/index.js#L55-L64).

**Comment by casoetan** [comment]
ok. Will look into that

Best, \Charles
via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=9.2.6&pv=10.12.1&source=email_footer_2]
On Sun, Nov 13, 2016 at 22:25, Alex <notifications@github.com> wrote:
If you're sure you're on the latest versions, all that I can recommend now is diving into the source and attempting to debug around here [https://github.com/jantimon/favicons-webpack-plugin/blob/master/index.js#L55-L64] .

**Comment by alexdrans** [comment]
Did you figure it out @casoetan ?

**Comment by c-h-** [comment]
@alexdrans Just to chime in here, I faced the issue of assets not injecting and realized it's because my HTML template didn't have a `<head>` section. Some tools let you strip "optional" HTML tags such as the head tag. Here's a webpack loader that does this: https://www.npmjs.com/package/htmlmin-loader 

Perhaps the plugin could detect when there's no head tag and inject below the doctype declaration in that case? Or warn the user with a `console.log` that no Head was detected to inject to?

**Comment by p4bloch** [comment]
For future reference, what happened to me is that I already had a `<link rel="icon">` from using `create-react-app`. Removing it made this plugin inject the generated icons just fine :)

**Comment by mezod** [comment]
Had the same issue, my fix was to remove legacy code from the template I had for htmlwebpackplugin v1. Looks like the solution to this is issue is most of the time to remove something from the index.html ...

**Comment by Ashwinvalento** [comment]
I too have the same issue, I noticed that when i add a custom template in webpack-html-loader , the favicon tags are not injected. But when i remove the template, the tags are present in the output.

My template is very simple.
```
<html>
<body>
  <div id="myApp">
  </div>
</body>
</html>
```
The porblem is that i need the div with id="myApp" . Any solutions ?

**Comment by alexdrans** [comment]
@Ashwinvalento, @c-h- 's answer might help you

**Comment by Ashwinvalento** [comment]
@alexdrans , Yep!! That was the issue, Thanks!

I simply added a empty head tag in my template and it worked.. My updated template is 
```
<html>
<head></head>
<body>
  <div id="myApp">
  </div>
</body>
</html>
```

**Comment by Truplic** [comment]
I have it working but xhtml flag of HtmlWebPackPlugin is not affecting injected tags, i.e. the injected makrup is not sclosed as required by xhtml.
