### ISSUE TITLE
Unnecessary requests to get the favicon in every route

### ISSUE THREAD

**Issue by aralroca** [jantimon/favicons-webpack-plugin#146]
Using a router as react-router; every time that the route change is doing a request to get again the favicon.

![image](https://user-images.githubusercontent.com/13313058/49941524-0c2b5d80-fee3-11e8-8dda-16511ed2f150.png)

This only happen using Chrome.

I guess that is happening for the order of links. Reordering the favicon link tags, 16x16 link before 32x32 fix this issue. No idea why...

**Comment by VincentVW** [comment]
I'm seeing the same issue, react router v4, Chrome only. Also tried to fiddle around with some options of the plugin but can't get it to work correctly with any settings.

**Comment by aralroca** [comment]
As I see `favicons-webpack-plugin` is using  `favicons` library. 

In this library was already solved this problem with this PR: https://github.com/itgalaxy/favicons/pull/235

The last version of `favicons` is `5.3.0` meanwhile the current one that is used here is `4.8.3`. Upgrading the version of this library should fix this problem

**Comment by jantimon** [comment]
Solved in favicons-webpack-plugin 1.0.0 - can you please give it a try?
