### ISSUE TITLE
Support xhtml flag

### ISSUE THREAD

**Issue by Truplic** [jantimon/favicons-webpack-plugin#147]
It seems that webapp-webpack-plugin doesn't consider xhtml flag set in html-webpack-plugin.
This is very important for xhtml pages that need to have all tags closed.

**Comment by jantimon** [comment]
This will be done with #158 as this will allow the html-webpack-plugin to take over the html generation.

**Comment by jantimon** [comment]
Will be released with 3.0 #184

**Comment by jantimon** [comment]
done with 3.0
