### ISSUE TITLE
Config for an output directory.

### ISSUE THREAD

**Issue by hally9k** [jantimon/favicons-webpack-plugin#15]
I wanted to direct all the output files into a directory named `favicons` but couldn't find the config option to do that. Have I missed something? 
Edit: I missed that the prefix config would allow for a path to be defined. Maybe a separate output config option might be a nice addition.

**Comment by jantimon** [comment]
You have to change the `prefix: 'icons-[hash]/'` setting

**Comment by dudewad** [comment]
I agree, `prefix` invokes filename prefix not output destination. I think it would be more "elegant" if there were an output property.

**Comment by wayou** [comment]
`prefix` may use for file name while `output` for the file path.

**Comment by amwill04** [comment]
@hally9k In the `generateIcons` function I have simply removed `entry.replace(/(href=[""])/g, '$1' + publicPath + pathPrefix)` and replace with `entry.replace(/(href=[""])/g, '$1' + path.join(publicPath, pathPrefix))`.

This has allowed me to use `prefix: '../images/favicons-[hash]/'`

Cant work out how to run tests on this apart from simply building my assets with webpack - but it works. Any help and Im happy to do a `pull request`

**Comment by jantimon** [comment]
Done in #157
