### ISSUE TITLE
Favicons not injected when webpack rebuilds with --watch

### ISSUE THREAD

**Issue by ilGuccio** [jantimon/favicons-webpack-plugin#152]
My configuration:

```
 new FaviconsWebpackPlugin({
                logo: path.resolve(__dirname, './static/img/favicon.png'),
                inject: true,
                persistentCache: true,
                emitStats: false,
                prefix: (argv.mode === "production") ? 'img/icons-[hash]/' : 'img/icons/',
                icons: {
                    android: (argv.mode === "production"),
                    appleIcon: (argv.mode === "production"),
                    appleStartup: (argv.mode === "production"),
                    coast: (argv.mode === "production"),
                    favicons: true,
                    firefox: (argv.mode === "production"),
                    opengraph: (argv.mode === "production"),
                    twitter: (argv.mode === "production"),
                    yandex: (argv.mode === "production"),
                    windows: (argv.mode === "production")
                }
            }),
```

**Comment by loxK** [comment]
It does work for me.

**Comment by Wolvan** [comment]
Can confirm the same thing happening for me. webpack --watch and then changing the HTML file causes it to not inject the links properly

**Comment by ronenmagid** [comment]
Same for me. `yarn start` will generate the icons and inject the HTML in place, but any change to my code which causes a watch update, will not have favicons and index.html will not be injected with them.

**Comment by tariqqubti** [comment]
Not sure if it is related to the issue, but I have two observations:

1. If CleanWebpackPlugin is added:
- If 'icons' folder already exists, it is removed and not regenerated on subsequent builds, also the links are not injected in the html
- If 'icons' folder does not exist, it is generated and links are added
2. If CleanWebpackPlugin is not added, so far it works

Can someone confirm if it is related somehow to CleanWebpackPlugin?

**Comment by Wolvan** [comment]
I'm using CleanWebpackPlugin as well

**Comment by jantimon** [comment]
Done in #157.

Can you please take a look?
