### ISSUE TITLE
emitStats && statsFilename Options don`t work.

### ISSUE THREAD

**Issue by Dryymoon** [jantimon/favicons-webpack-plugin#16]
Hi.
My config:
`new FaviconsWebpackPlugin({
      logo: './static/favicon.png',
      prefix: 'icons-[hash]/',
      emitStats: false,
      statsFilename: 'iconstats-[hash].json',
      persistentCache: true,
      title: 'Domik',
      inject: false,
      icons: {
        android: true,
        appleIcon: true,
        appleStartup: true,
        coast: false,
        favicons: true,
        firefox: true,
        opengraph: false,
        twitter: false,
        yandex: false,
        windows: false
      }
    }),`

And option "statsFilename" don`t generate any file.
Option "emitStats" down work and all stats is emitted.

**Comment by NikitaRzm** [comment]
Confirm.
Stats always is emitted despite of flag 'emitStats: false'.

**Comment by jantimon** [comment]
Fixed in favicons-webpack-plugin 1.0.0
