### ISSUE TITLE
What is manifest.webapp?

### ISSUE THREAD

**Issue by lucasvazq** [jantimon/favicons-webpack-plugin#160]
And where metatags make refer to him?

**Comment by jantimon** [comment]
It is generated by https://github.com/itgalaxy/favicons - please take a look here for additional information.

**Comment by lucasvazq** [comment]
@jantimon it's outdated thing related to the discontinued Firefox Os

https://developer.mozilla.org/en-US/docs/Archive/B2G_OS/Firefox_OS_apps/Building_apps_for_Firefox_OS/Manifest

I'm going to report this to favicons module

**Comment by jantimon** [comment]
Thanks a lot :)
