### ISSUE TITLE
Yarn warning with webpack 3.x

### ISSUE THREAD

**Issue by okovpashko** [jantimon/favicons-webpack-plugin#161]
Hello.
I still use **webpack 3** and after updating **favicons-webpack-plugin** to **v1.x.x** I got the following warning from yarn:
```shell
warning "favicons-webpack-plugin > cache-loader@3.0.1" has incorrect peer dependency "webpack@^4.0.0".
```
Seems like the too new version of **cache-loader** is used that requires webpack 4

Is it possible to align dependencies for webpack 3 as well?

**Comment by jantimon** [comment]
The last **webpack 3** version was released one year ago:

https://www.npmjs.com/package/webpack/v/3.12.0

The webpack team is preparing to release **webpack 5**.

It would be a lot of work to maintain webpack 3, 4 and 5 as many internals have changed.

Would it be possible for you to migrate to webpack 4?

**Comment by okovpashko** [comment]
@jantimon sorry for not replying for so long. Yes it's possible. I just noticed you about this issue as there's no any info in changelog that webpack 3 support is dropped.
