### ISSUE TITLE
Generating multiple favicons

### ISSUE THREAD

**Issue by theopolisme** [jantimon/favicons-webpack-plugin#17]
Is there any way to use this plugin to generate multiple favicons? In our case, a different favicon for each entry point is the example usecase (using webpack to generate bundles for a multi-tenant webapp).

A potential API could be something like this:

```
plugins: [
  new FaviconsWebpackPlugin({
    logo: '[name].png',
    prefix: '[name]/icons',
    ...
]
```

Is there any way to do this currently / is the additional functionality a possibility?

**Comment by jantimon** [comment]
Great idea but unfortunately this is also quite complex.
Open for prs
