### ISSUE TITLE
builds favicons on one run, then does not on the next with CleanWebpackPlugin

### ISSUE THREAD

**Issue by joepagan** [jantimon/favicons-webpack-plugin#172]
I cannot see an existing issue, but, the behaviour is mentioned here...

https://github.com/jantimon/favicons-webpack-plugin/issues/152#issuecomment-507359203

run favicons task, 
favicons are built

run favicons task again
favicons get deleted by CleanWebpackPlugin with:
```
cleanOnceBeforeBuildPatterns: [
          'resources/favicons',
        ],
```
favicons are not generated

I presume this is because the favicons are built before CleanWebpackPlugin in the chain and that we cannot solve with a specific an order in our configs?

**Comment by sHooKDT** [comment]
+1 for the issue.
Found favicons disappeared on production today and it's reeeally bad.
Maybe we need to emit favicons in a later phase.

**Comment by jantimon** [comment]
Open for pull requests

**Comment by joepagan** [comment]
I can confirm that this no longer appears to be an issue with:

```bash
"favicons-webpack-plugin": "^1.0.2",
"webpack": "^4.41.2",
    "webpack-cli": "^3.3.9",
    "webpack-dev-server": "^3.8.2",
    "webpack-merge": "^4.2.2"
```
