### ISSUE TITLE
Asset Versioning

### ISSUE THREAD

**Issue by dNitro** [jantimon/favicons-webpack-plugin#175]
Normally for favicon's long term caching, a version parameter is added to the URL: ( `/assets/favicon.ico?v=1` ).

According to [favicons Issue #80](https://github.com/itgalaxy/favicons/issues/80), the maintainers believe this addition is a post favicons process! As this plugin is a post favicons process could we have an option to enable `versioning` so all URLs would have a suffix like: `?v=1`.

Then setting `versioning: true` will produce the following URLs:
```html
...
<link rel="shortcut icon" href="/assets/favicon.ico?v=qmLv8rvz">
<link rel="icon" type="image/png" sizes="16x16" href="/assets/favicon-16x16.png?v=qmLv8rvz">
<link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon-32x32.png?v=qmLv8rvz">
...
```

**P.S.**: I am aware that there is a `[hash]` substitution that we could use as a **prefix path** for generated assets, but what if we wanted to input assets in the server **root** ?! how then we could add versioning to them ?

**Comment by georgyfarniev** [comment]
Yes, I suffer from same issue. @jantimon please help us.

**Comment by georgyfarniev** [comment]
This is very important feature, since this is how all caching works with webpack.

**Comment by jantimon** [comment]
You can use `[hash]` inside the `prefix` option

**Comment by georgyfarniev** [comment]
> You can use `[hash]` inside the `prefix` option

Hello, thanks reform reply. I know about this option, but it will require me to change many files path even if only one was changed, which is inefficient. Also it will require me to add another separate hashed directory, which is very inconvenient. Why not just introduce option with hashing files individually? It is now most people use hashing, it’s more efficient and intuitive. 

Also, I checked source of both favicons and your plugin and it seems possible to implement on plugin side due how favicons api work. 

Thanks. Regards, Georgy

**Comment by mateuszkosmider** [comment]
Any plans for this issue? It would be great to see this feature.

**Comment by jantimon** [comment]
Sorry @mateuszkosmider there is no plan to implement this feature.  
But I am open for pull request if you want to take a look at it.

**Comment by evictor** [comment]
+1

Using hash in filename is a de facto standard at this point.

**Comment by jantimon** [comment]
The change could be done here: https://github.com/jantimon/favicons-webpack-plugin/blob/ed6c0217e349675d09ab456139b96918ef6d727a/src/compiler.js#L69-L75
