### ISSUE TITLE
Inject favicons tags into custom position using ejs template

### ISSUE THREAD

**Issue by hypernova7** [jantimon/favicons-webpack-plugin#176]
For example:
```html
<head>
    <!-- Seo Tags from Google, Facebook, Twitter, etc-->
    <%- htmlWebpackPlugin.files.favicons.html %>
    <!-- script tags from Google Analytics, etc -->
</head>
```

Output:
```html
<head>
    <!-- Seo Tags from Google, Facebook, Twitter, etc-->
    <link rel="icon" href="...">
    <meta name="..." content="...">
    <!-- etc -->
    <!-- script tags from Google Analytics, etc -->
</head>
</head>
```

**Comment by CoderAmigo** [comment]
Hi Eddy, I managed to solve this problem!

By creating a micro plugin using hooks.

It was required to use [WebappWebpackPlugin](https://github.com/brunocodutra/webapp-webpack-plugin) this fork FaviconsWebpackPlugin with implemented support for the hook [webappWebpackPluginBeforeEmit](https://github.com/brunocodutra/webapp-webpack-plugin#hooks) but unfortunately with the options `mode` and `devMode` remaining.
Jan, Bruno if you are reading this please give the opportunity to inject it into a custom template from the box or add support for hooks to FaviconsWebpackPlugin or the `devMode` option in the fork. And then you have to use crutches =(

The crutch itself:

```
new (class FaviconsTransponderWebpackPlugin {
    apply(compiler) {
        let lincIcons = [];
        compiler.hooks.make.tap("FaviconsTransponderWebpackPlugin", (compilation) => {
            compilation.hooks.webappWebpackPluginBeforeEmit.tapAsync("FaviconsTransponderWebpackPlugin", (data, cb) => {
                lincIcons = data.tags.map((tag) => {
                    let tagName = tag.split(' ')[0].slice(1);
                    tag = tag.slice(tagName.length + 1).slice(2, -1);
                    let tagAttributes = tag.split('" ').reduce((attrs, attr) => {
                        attr = attr.split('="');
                        attrs[attr[0]] = attr[1];
                        return attrs;
                    }, {});
                    return tagAttributes;
                });
                return cb(null, data);
            });
        });
        compiler.hooks.make.tap('FaviconsTransponderWebpackPlugin', (compilation) => {
            compilation.hooks.htmlWebpackPluginBeforeHtmlGeneration.tapAsync('FaviconsTransponderWebpackPlugin', (data, cb) => {
                data.assets.icon = (data.assets.icon || []).concat(lincIcons);
                return cb(null, data);
            });
        });
    }
})()
```

In your .ejs template:

```
<%if (Array.isArray(htmlWebpackPlugin.files.icon)) {
    for (let icon of htmlWebpackPlugin.files.icon) { %>
    <link<% for (key in icon) { %> <%= key %>="<%= icon[key] %>"<% } %>><%
    }
} %>
```

Only works with WebappWebpackPlugin use ```new WebappWebpackPlugin ({ otions... })```.

Explanations:

Why are html lincs parsed? The first reason, for greater total flexibility, is the ability to calculate the functional by adding modifications to the inserted html tags.
The second reason, I tried to get link icon tags in the form of an object with parameters, but from `compilation.hooks.webappWebpackPluginBeforeEmit.tapAsync` only html and something came in the format `Buffer`, I could not figure out why `Buffer` and what would be kept in it.

This is my first experience in creating the use of webpack hooks and in general the first experience of writing a plugin for webpack, so I could not do everything absolutely right, but everything works!
For example, I have a suspicion that I am transferring incorrect names to hooks tap, although in this case it does not affect anything.

**Comment by hypernova7** [comment]
> Hi Eddy, I managed to solve this problem!
> 
> By creating a micro plugin using hooks.
> 
> It was required to use [WebappWebpackPlugin](https://github.com/brunocodutra/webapp-webpack-plugin) this fork FaviconsWebpackPlugin with implemented support for the hook [webappWebpackPluginBeforeEmit](https://github.com/brunocodutra/webapp-webpack-plugin#hooks) but unfortunately with the options `mode` and `devMode` remaining.
> Jan, Bruno if you are reading this, please give the opportunity to inject it into a custom template from the box or add support for hooks to FaviconsWebpackPlugin or the `devMode` option in the fork. And then you have to use crutches =(
> 
> The crutch itself:
> 
> ```
> new (class FaviconsTransponderWebpackPlugin {
>     apply(compiler) {
>         let lincIcons = [];
>         compiler.hooks.make.tap("FaviconsTransponderWebpackPlugin", (compilation) => {
>             compilation.hooks.webappWebpackPluginBeforeEmit.tapAsync("FaviconsTransponderWebpackPlugin", (data, cb) => {
>                 lincIcons = data.tags.map((tag) => {
>                     let tagName = tag.split(' ')[0].slice(1);
>                     tag = tag.slice(tagName.length + 1).slice(2, -1);
>                     let tagAttributes = tag.split('" ').reduce((attrs, attr) => {
>                         attr = attr.split('="');
>                         attrs[attr[0]] = attr[1];
>                         return attrs;
>                     }, {});
>                     return tagAttributes;
>                 });
>                 return cb(null, data);
>             });
>         });
>         compiler.hooks.make.tap('FaviconsTransponderWebpackPlugin', (compilation) => {
>             compilation.hooks.htmlWebpackPluginBeforeHtmlGeneration.tapAsync('FaviconsTransponderWebpackPlugin', (data, cb) => {
>                 data.assets.icon = (data.assets.icon || []).concat(lincIcons);
>                 return cb(null, data);
>             });
>         });
>     }
> })()
> ```
> 
> In your .ejs template:
> 
> ```
> <%if (Array.isArray(htmlWebpackPlugin.files.icon)) {
>     for (let icon of htmlWebpackPlugin.files.icon) { %>
>     <link<% for (key in icon) { %> <%= key %>="<%= icon[key] %>"<% } %>><%
>     }
> } %>
> ```
> 
> Only works with WebappWebpackPlugin use `new WebappWebpackPlugin ({ otions... })`.
> 
> Explanations:
> 
> Why are html lincs parsed? The first reason, for greater total flexibility, is the ability to calculate the functional by adding modifications to the inserted html tags.
> The second reason, I tried to get link icon tags in the form of an object with parameters, but from `compilation.hooks.webappWebpackPluginBeforeEmit.tapAsync` only html and something came in the format `Buffer`, I could not figure out why `Buffer` and what would be kept in it.
> 
> This is my first experience in creating the use of webpack hooks and in general the first experience of writing a plugin for webpack, so I could not do everything absolutely right, but everything works!
> For example, I have a suspicion that I am transferring incorrect names to hooks tap, although in this case it does not affect anything.

Not what i was looking for

**Comment by CoderAmigo** [comment]
And what is wrong?

**Comment by hypernova7** [comment]
@CoderAmigo the properties of the meta tags, would be within the link tags, and would result in an incorrect html and would affect the SEO of the page.

**Comment by CoderAmigo** [comment]
@hypernova7 No, they will not do. Check it out.

**Comment by hypernova7** [comment]
The correct thing would be to pass the html that returns favicons-webpack-plungin to an object of html-webpack-plugin. 

Something like that:

```javascript
new HtmlWebpackPlugin({
  htmlFavicons: Object // Object returned from FaviconsWebpackPlugin with html output
})
```
ejs template
```html
<%- htmlWebpackPlugin.options.htmlFavicons %>
```
html returned
```html
<meta name="..." content="...">
<link rel="..." href="..." type="...">
<!-- etc -->
```

**Comment by hypernova7** [comment]
Sorry for my English, I still don't know how to write very well in English or speak it xD

**Comment by CoderAmigo** [comment]
Apparently your .ejs template is a "children's" - a simple variation.

 the finished HTML is not true. Look at how advanced templates work.
For example [html-webpack-template](https://github.com/jaketrent/html-webpack-template) look at it [index.ejs](https://github.com/jaketrent/html-webpack-template/blob/master/index.ejs)
In principle, implementing it so that the ready-made html is sent to the htmp-webpack-plugin will not be a serious mistake, but it will not be very flexible.

> `<% - htmlWebpackPlugin.options.htmlFavicons %>`

You suggested putting the data received from the favicon plugin into `htmlWebpackPlugin.options` in options, this is absolutely not true.

And now, regarding the final result of the assembly, the decision that I gave initially leads to that result of the assembly you are talking about: meta tags separately, link tags separately and do not overlap in any way, but in what sequence they turn out it all depends on the template, just add to the right place:

```
<%if (Array.isArray(htmlWebpackPlugin.files.icon)) {
    for (var icon of htmlWebpackPlugin.files.icon) { %>
    <link<% for (var key in icon) { %> <%= key %>="<%= icon[key] %>"<% } %>><%
    }
} %>
```

In general, to do exactly as you want is a very simple task, just compile the html not in the tape but the functions of my `FaviconsTransponderWebpackPlugin`

Just change here:

```
data.assets.icon = (data.assets.icon || []).concat(lincIcons);
return cb(null, data);
```

And put the assembled html wherever you want. For example: `data.assets.faviconHtml` will be available in the template like this: `<%= htmlWebpackPlugin.files.faviconHtml %>`. But this is not right!

Or remove the html parsing from the code and transfer it in its original form, the original data is in `data.tags` 6 line in `FaviconsTransponderWebpackPlugin`.

**Comment by hypernova7** [comment]
@CoderAmigo Thanks, I understood.  and excuse me, I'm new to this for webpack plugins xD

**Comment by hypernova7** [comment]
@CoderAmigo And thanks for the code, I'll use it if it doesn't bother you.

**Comment by CoderAmigo** [comment]
@hypernova7 Thank, I will be glad if my code will help in your work.

**Comment by CoderAmigo** [comment]
@hypernova7 It seems I initially did not quite understand what you were talking about.
I wrote down all the tags, substituting the name of the `link` tag, I initially did not notice that the favicon plugin generates not teloko `link' tags but also `meta` tags.
And it turned out just what you possibly talked about, link tags with meta tag attributes were generated, you originally talk to me **about this**?

So I fixed it! + made a small but cool code refactoring).

... Updated the code in my posts.

**Comment by hypernova7** [comment]
@CoderAmigo If that's why I told you that, I was going to generate a badly formed HTML hahahaha

**Comment by hypernova7** [comment]
@CoderAmigo Thank you for modifying the code you showed me before. I will close this post

**Comment by CoderAmigo** [comment]
@hypernova7 The problem is not properly resolved. You can open this issue.

**Comment by hypernova7** [comment]
@CoderAmigo It is done

**Comment by CoderAmigo** [comment]
Cast summon spell, @brunocodutra, =)

**Comment by ioulian** [comment]
@CoderAmigo Your code doesn't work anymore (not with 1.0.2 and not with 3.x version). What I'm trying to do is to get all the tags and save them to a file (to be manually injected by PHP). Previously I could tap into "webappWebpackPluginBeforeEmit" hook and get all the tags, but this is not possible anymore as "webappWebpackPluginBeforeEmit" hook doesn't exist enymore.

Have you managed to fix this?

**Comment by jantimon** [comment]
Here is an example which is using 

[html-webpack-plugin 4.x](https://www.npmjs.com/package/html-webpack-plugin/v/4.0.0-beta.11)
and favicons-webpack-plugin 3.x

https://github.com/jantimon/favicons-webpack-plugin/tree/master/example/no-inject

Your `<head>` might look like this:

https://github.com/jantimon/favicons-webpack-plugin/blob/47bf751d3e9c945c77fbd853d46c8ce70d08b338/example/no-inject/src/index.html#L4-L10

**Comment by ioulian** [comment]
> Here is an [example](https://github.com/jantimon/favicons-webpack-plugin/tree/master/example/no-inject) which is using
> 
> * [html-webpack-plugin 4.x](https://www.npmjs.com/package/html-webpack-plugin/v/4.0.0-beta.11)
> * favicons-webpack-plugin 3.x
> 
> https://github.com/jantimon/favicons-webpack-plugin/tree/master/example/no-inject
> 
> Your `<head>` might look like this:
> 
> https://github.com/jantimon/favicons-webpack-plugin/blob/47bf751d3e9c945c77fbd853d46c8ce70d08b338/example/no-inject/src/index.html#L4-L10

Yes, this is the route I chose to do it, but it does add other tags (like css links or the head tag) that are not needed. You can create an empty .ejs file with this inside:

```ejs
<%= htmlWebpackPlugin.tags.headTags.filter((tag) => tag.toString().indexOf('.css"') === -1).join('') %>
```

This will output all tags without .css files. This works ok as a quick hack

**Comment by jantimon** [comment]
You can also tell the html webpack to exclude all chunks if you don't want it to provide any js or css files.

**Comment by CoderAmigo** [comment]
@ioulian I assume that you have mixed up [favicons-webpack-plugin](https://github.com/jantimon/favicons-webpack-plugin) and [webapp-webpack-plugin](https://github.com/brunocodutra/webapp-webpack-plugin). Current actual stable version [webapp-webpack-plugin](https://github.com/brunocodutra/webapp-webpack-plugin) is 2.7.1

And I believe that @jantimon perhaps in the [favicons-webpack-plugin 3.x](https://github.com/jantimon/favicons-webpack-plugin) version, realized the possibility of solving the problem under discussion in a more correct and concise way.

```js
new FaviconsWebpackPlugin({
    logo: 'logo.svg',
    inject: htmlPlugin => { 
         // Your complementary data for the .ejs template code is here
         return false
    }
})
```
But all this will still look like a hack, but not a beautiful concise solution.

**Comment by jantimon** [comment]
We merged webapp back into the 2.x version of the favicons-webpack-plugin

You can disable any html-webpack-plugin if you set `favicons:false`

**Comment by hypernova7** [comment]
> 
> 
> Here is an [example](https://github.com/jantimon/favicons-webpack-plugin/tree/master/example/no-inject) which is using
> 
>     * [html-webpack-plugin 4.x](https://www.npmjs.com/package/html-webpack-plugin/v/4.0.0-beta.11)
> 
>     * favicons-webpack-plugin 3.x
> 
> 
> https://github.com/jantimon/favicons-webpack-plugin/tree/master/example/no-inject
> 
> Your `<head>` might look like this:
> 
> https://github.com/jantimon/favicons-webpack-plugin/blob/47bf751d3e9c945c77fbd853d46c8ce70d08b338/example/no-inject/src/index.html#L4-L10


This is what I was referring to, thank you very much. (Sorry for replying so late, I mistakenly disabled notifications for this issue and just realized)

**Comment by jantimon** [comment]
Thanks for the update :)
