### ISSUE TITLE
Add support for relative paths 

### ISSUE THREAD

**Issue by matanui159** [jantimon/favicons-webpack-plugin#177]
Would help in situations like gitlab pages where it's usually in a subfolder

Apparently `manifest.json` does support relative paths as well

**Comment by Tofandel** [comment]
This is basically a duplicate of https://github.com/jantimon/favicons-webpack-plugin/issues/162

If it wasn't for this issue, the plugin would support relative path

**Comment by jantimon** [comment]
Fixed and released as https://www.npmjs.com/package/favicons-webpack-plugin/v/2.0.0
