### ISSUE TITLE
Microsoft Edge 42.17134.1098.0 (favicons-webpack-plugin v1.0.2)

### ISSUE THREAD

**Issue by Legends** [jantimon/favicons-webpack-plugin#178]
Works with FF and Chrome ootb, but in Edge the favicon doe snot show up.

> The default configuration will automatically generate webapp manifest files along with 44 different icon formats as appropriate for iOS devices, Android devices, Windows Phone and various desktop browsers out of your single logo.png.

They seem not to be generated. I use the provided[ basic configuration](https://github.com/jantimon/favicons-webpack-plugin#basic-usage) and also `HtmlWebapackPlugin`.

This gets generated on my side:

![image](https://user-images.githubusercontent.com/966368/69681300-f68c5500-10ad-11ea-84ce-0f712a8dd7fc.png)

**Comment by jantimon** [comment]
The dev build uses some shortcuts to increase speed.

Do you talk about the dev or prod build?

**Comment by Legends** [comment]
It's webpack dev build. Didn't try in prod mode.

**Comment by jantimon** [comment]
You can use `mode:'webapp'` to always make a full favicon build

**Comment by Legends** [comment]
I have download a `logo.png` from somewhere to be my `favicon` for testing.
Now it generates all icons, but the favicon is still not showing up in 'MS Edge' browser.

![image](https://user-images.githubusercontent.com/966368/69710773-45fb7100-1100-11ea-9d4d-e0a231694661.png)

Anything else I have to consider?

**Comment by jantimon** [comment]
I am not an expert on MS Edge favicon formats - maybe you can take a look at the favicons project

**Comment by Legends** [comment]
Good, I will check it out, thanks for your efforts!
