### ISSUE TITLE
Update favicons to 5.5.0

### ISSUE THREAD

**Issue by buzz** [jantimon/favicons-webpack-plugin#179]
**favicons-5.5.0** was just released. It fixes an build issue by updating [sharp](https://github.com/lovell/sharp) to the current version.

Would it be possible to update favicons and release a new version? 
Thank you very much.

Related: https://github.com/itgalaxy/favicons/issues/292

**Comment by jantimon** [comment]
Unfortunately 5.5.0 breaks compatibility to webpack ecosystem:

https://github.com/itgalaxy/favicons/issues/293

Maybe we can include it for the webpack 5 version

**Comment by jordinl83** [comment]
@jantimon what exactly would this change break? We can't upgrade to Node 13 until this change is made.

**Comment by merit-mthompson** [comment]
Hoping to bump this issue. We have to remove this plugin to have our builds succeed and that's not awesome.
What needs to be done to get things working? I understand the pragmatic approach to keeping things Webpack 4 (Node 6) compatible but is there maybe something that can be done to work around that? Maybe cutting a major version release that addresses build issues?

**Comment by asvetliakov** [comment]
@merit-mthompson if you're using yarn you can try to add ```"resolutions": { "favicons": "5.5.0" }``` into your ```package.json```. There may be npm analogue too

**Comment by GauthierPLM** [comment]
I can confirm that currently, with node 13, I am unable to use this plugin. The build process fails (as reported in itgalaxy/favicons#293) and I had to downgrade to node 12 to use it.

**Comment by ericcirone** [comment]
Using yarn with `resolutions` for sharp works on node 13.

```
"resolutions": {
		"**/**/sharp": "^0.23.4"
	}
```

**Comment by jantimon** [comment]
Fixed and released as https://www.npmjs.com/package/favicons-webpack-plugin/v/2.0.0
