### ISSUE TITLE
Too much info in my command line

### ISSUE THREAD

**Issue by dalgard** [jantimon/favicons-webpack-plugin#18]
Can I stop this plugin from outputting a long list of generated files to my console?

**Comment by jantimon** [comment]
This is done by webpack - just tell webpack to be less verbose

**Comment by dalgard** [comment]
I imagined as much. The problem is, that I can't turn off that output without missing all the stuff that I actually want to see.

Would it be possible to create a simple option in this package to stop outputting the favicon files only?

**Comment by jantimon** [comment]
Not that I know as it is done by webpack not by this plugin - if you find a solution please let me know

**Comment by tkrotoff** [comment]
[favicons](https://github.com/evilebottnawi/favicons) generates too many files (favicons-webpack-plugin's underlying lib - hence its name).
See https://github.com/evilebottnawi/favicons/issues/140
