### ISSUE TITLE
outputPath vs publicPath vs prefix vs different modes seems broken

### ISSUE THREAD

**Issue by cjblomqvist** [jantimon/favicons-webpack-plugin#185]
I find it quite unclear what each of these 3 options do, especially considering the different modes. In light mode for example, code inspection tells me that outputPath is not used at all (since this.options.outputPath is not referenced anywhere).

I got my version working after a lot of testing (I have html injection as well, so need to match with that), but I thought it be good to know that there are som discrepencies with this.

Thanks for your effort and plugin!

**Comment by vikkrantxx7** [comment]
I think a little documentation will be really helpful. Like I can't find anything about `manifestRelativePaths` option which is a lifesaver.
