### ISSUE TITLE
Support for RealFaviconGenerator

### ISSUE THREAD

**Issue by phbernard** [jantimon/favicons-webpack-plugin#187]
favicons-webpack-plugin could support [RealFaviconGenerator](https://realfavicongenerator.net/) in addition to [favicons](https://github.com/itgalaxy/favicons).

What is the point of supporting RFG?

- **No brainer UI** - The favicon-related tasks are done from RFG web site, so you don't have anything to learn/read.
- **Instant feedback** - You can see how your icons will look like on desktop, Google search results, iOS, etc.
- **Handy edition options** - You can quickly edit your icons so they look great on various platforms.

I'm the author of RealFaviconGenerator and I'm basically asking for permission to submit a PR. Of course, it would be non-breaking. RFG would be a second choice, via an option.

As an aside, RFG would reference favicons-webpack-plugin. For an example of how that could look like, see https://realfavicongenerator.net/favicon/gulp .

**Comment by jantimon** [comment]
Does RealFaviconGenerator work without internet connection?

**Comment by phbernard** [comment]
It doesn't.

I discussed with Hayden Bleasel from the favicons plugin years ago about this. At that time, there were no JS native lib that could cover all RFG options. Maybe that has changed, but I didn't took time to investigate this.

**Comment by jantimon** [comment]
Okay I thought that might have changed over time. I really like `RealFaviconGenerator` and it was one reason why I created the favicons-webpack-plugin.  

It has the following goals:

- simple integration to the html-webpack-plugin
- fast usage during dev mode
- no internet connection required for the build server
- easy configuration

So my intention was also a no brainer api similar to your generator. Unfortunately favicons are way more complicated than it seem (you probably know that even better than me). Still the idea was very similar to your website:

```js
new FaviconsWebpackPlugin('/path/to/logo.png')
```

I am not sure which value RealFaviconGenerator could add to this project but I am totally open for suggestions.

**Comment by phbernard** [comment]
Sometimes the original image is not enough. A classic example is the Touch icon. Because iOS fills the transparent regions with black when adding to home screen, you almost never want to use your transparent image as is. RFG allows to know about the issue, and to fix it by adding a solid background and slight margins around your image.

This is definitely not rocket science, but more than a quarter of RFG's users are using this option. A sign that their raw images are not enough after all.

This said, I understand the off line requirement. Unfortunately, I have no short-term solution for this. Appart from a warning notice "your build server will need an internet connection if you use RFG", I can't see any workaround. If that doesn't fit favicons-webpack-plugin spirit, hey, that's not a problem, no hard feeling :-)

**Comment by jantimon** [comment]
From what I know [favicons](https://github.com/itgalaxy/favicons) does now also allow to set backgrounds for operation systems.  

I guess your knowledge can improve `favicons-webpack-plugin` a lot so feel free to play around with it and let me know what you think.

Here is a codesandbox with a basic configuration to get you started:  
https://codesandbox.io/s/favicons-webpack-plugin-8wltc
