### ISSUE TITLE
Wrong HTML snippet in HTML injection section

### ISSUE THREAD

**Issue by bravokiloecho** [jantimon/favicons-webpack-plugin#188]
The snippet describing what's added to the Head, that begins...
```
<link rel="apple-touch-icon" sizes="57x57" href="/assets/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/assets/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/assets/apple-touch-icon-72x72.png">
...
```
does not match the filenames of the icons that are generated.

For example, the snippet references: 
`<link rel="apple-touch-startup-image" media="(device-width: 768px) and (device-height: 1024px) and (orientation: landscape) and (-webkit-device-pixel-ratio: 2)" href="/pwa/apple-touch-startup-image-1496x2048.png" />`

but the closest icon for this is `apple-touch-startup-image-1536x2048.png`.

Could this snippet in the README be updated? Thanks!

**Comment by bravokiloecho** [comment]
Also the link underneath the snippet doesn't work: https://github.com/jantimon/favicons-webpack-plugin/blob/master/test/fixtures/expected/html

**Comment by jantimon** [comment]
Can you please send a pr?
