### ISSUE TITLE
favicons-webpack-plugin v3.0.1 incompatible with html-webpack-plugin v3.2.0?

### ISSUE THREAD

**Issue by nthurnau** [jantimon/favicons-webpack-plugin#189]
The project using the latest version (v3.0.1) of this favicons-webpack-plugin throws an error when used alongside html-webpack-plugin v3.2.0. It fails to compile and provides the following message:
`ERROR in FaviconsWebpackPlugin - This FaviconsWebpackPlugin version is not compatible with your current HtmlWebpackPlugin version.
Please upgrade to HtmlWebpackPlugin >= 4 OR downgrade to FaviconsWebpackPlugin 2.x`

I'm currently using webpack v4.41.2. The project does not use create-react-app. 

html-webpack-plugin's latest released version is 3.2.0, so I am not sure why the error message is prompting me to either downgrade favions-webpack-plugin or upgrade to a version of html-webpack-plugin that doesn't yet exist 😄 - any feedback would be great. I also tried switching the path from absolute to relative with no luck.  Here is my webpack setup for reference:
```
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const Dotenv = require('dotenv-webpack');
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
const FaviconsWebpackPlugin = require('favicons-webpack-plugin');

module.exports = env => ({
  entry: ['react-hot-loader/patch', './src/index.tsx'],
  resolve: {
    extensions: ['.ts', '.tsx', '.js'],
    alias: {
      opsware: path.resolve(__dirname, 'src'),
      tests: path.resolve(__dirname, 'jest'),
      'react-dom': '@hot-loader/react-dom',
    },
  },
  output: {
    path: path.join(__dirname, '/dist'),
    filename: 'bundle.[hash].js',
    publicPath: '/',
  },
  module: {
    rules: [
      {
        test: /\.(ts|js)x?$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
        },
      },
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader'],
      },
      {
        test: /\.(woff|woff2|eot|ttf|otf)$/,
        use: ['file-loader'],
      },
    ],
  },
  plugins: [
    new Dotenv({
      safe: './env.example',
      path: env.NODE_ENV ? `./.env.${env.NODE_ENV}` : './env.development',
    }),
    new HtmlWebpackPlugin({
      template: './public/index.html',
      filename: './index.html',
    }),
    new ForkTsCheckerWebpackPlugin({}),
    new FaviconsWebpackPlugin('assets/favicon.png'),
  ],
  devServer: {
    historyApiFallback: true,
    overlay: true,
  },
});

```

**Comment by jantimon** [comment]
html webpack plugin 4 is beta

**Comment by inoyakaigor** [comment]
@jantimon there's always the possibility that it will never be released as production-ready so making the production build of your plugin dependent on beta of other is a bad idea in my opinion.

**Comment by jantimon** [comment]
If you are not happy with using the beta (which is downloaded millions times per week) you can instead use html-webpack-plugin 3.2 and favicons-webpack-plugin 2.x

**Comment by jantimon** [comment]
version 4 is now released as stable
