### ISSUE TITLE
Full use example?

### ISSUE THREAD

**Issue by isaachinman** [jantimon/favicons-webpack-plugin#19]
Sorry if I'm being dense, but I don't see how this is actually useful if you don't use the html-webpack-plugin? 

Yes, it bounces 32 different icons to a directory called icons-[hash], but how do we then use these favicons? I'm rendering out my page via React server-side, and I can't really connect the dots. A full example would be helpful. Cheers.

**Comment by jantimon** [comment]
It generates a JSON with all information about the icons including the html for the head

**Comment by liitfr** [comment]
@jantimon thanks for your plugin ! 
I'm using webpack with [spike](http://www.spike.cf) therefore I don't use html webpack plugin.
Right now i'm using your plugin and afterwards run a gulp file that injects html code generated in json output file in every html pages.

I would like to know if I can get rid of gulp and call your plugin output directly during webpack compiles.
Thanks again ! Mat.

**Comment by othyn** [comment]
Just wondering; how can I parse the JSON html output into the head during a webpack build?

I'm not using the html plugin as I have no need for it, but this plugin is exceedingly helpful in it's own right and I would like to make use of it.
