### ISSUE TITLE
Installation instruction (deep dependency): missing dependency causing invalid pointer

### ISSUE THREAD

**Issue by GerkinDev** [jantimon/favicons-webpack-plugin#190]
Hey there ! I just spent the last 3 hours tracking down a big ol' CPP error when using your lib. Here's the terminating output I had: 

```
10% building 7/7 modules 0 activefree(): invalid pointer
[1]    73232 abort (core dumped)  npm run build
```

I've managed to find the issue, that was linked to [sharp](https://www.npmjs.com/package/sharp), required by your dependency [favicons](https://www.npmjs.com/package/favicons?activeTab=dependencies). The problem was that one of sharp's binary dependency was missing on my machine.

So here's the install instructions from sharp: https://sharp.pixelplumbing.com/install#freebsd. I just had to install `vips` & `vips-devel`, rebuild `sharp`, and it worked like a charm :)

I'm just posting it in case anybody stumble on this.

Cheers !

**Comment by jantimon** [comment]
fixed in 5.0.0
