### ISSUE TITLE
inject bag HtmlWebpackPlugin

### ISSUE THREAD

**Issue by maystrenkoYurii** [jantimon/favicons-webpack-plugin#194]
Favicons ingected only if HtmlWebpackPlugin options inject = true. But if HtmlWebpackPlugin options inject = true favicons injected with js bundles. Am using ssr and inject js bundled chanks programatically as a result dublicate js bundled chanks. Its bad. 

html-webpack-plugin: 4.0.1,
favicons-webpack-plugin: 3.0.1

favicons-webpack-plugin: "2.1.0" good work

**Comment by jantimon** [comment]
Can you please provide a very simple example?

**Comment by maystrenkoYurii** [comment]
@jantimon 
Favicons injected only if html-webpack-plugin property inject true. But if inject=true in html-webpack-plugin =>  favicon injected with bundled chank js and css. But must be only favicons. Other chancks and css i injected on server => duplicate chancks
![Снимок экрана от 2020-03-26 20-44-43](https://user-images.githubusercontent.com/23016311/77684775-17ed4700-6fa3-11ea-80a4-e74c940d6cdd.png)
![Снимок экрана от 2020-03-26 20-52-20](https://user-images.githubusercontent.com/23016311/77685189-ba0d2f00-6fa3-11ea-8c9d-8498571aec65.png)
![Снимок экрана от 2020-03-26 20-39-19](https://user-images.githubusercontent.com/23016311/77684033-05bed900-6fa2-11ea-945e-dd3aca298c96.png)
![Снимок экрана от 2020-03-26 20-39-34](https://user-images.githubusercontent.com/23016311/77684034-06f00600-6fa2-11ea-8f50-a958e261389f.png)
![Снимок экрана от 2020-03-26 20-39-56](https://user-images.githubusercontent.com/23016311/77684036-06f00600-6fa2-11ea-89c6-e1f1a789c2b0.png)

**Comment by id247** [comment]
Same issue. Can not insert favicons with 3.0.1
