### ISSUE TITLE
explain advantages provided here over directly using an svg icon as the favicon

### ISSUE THREAD

**Issue by iambumblehead** [jantimon/favicons-webpack-plugin#199]
explain advantages provided here over directly using an svg icon as the favicon

now that chrome and firefox support svg favicon, it would be nice to see a section of the README explain the value that is added from using this plugin.

https://caniuse.com/#feat=link-icon-svg

**Comment by RplusSoundOn** [comment]
svg favicon with fallback
```
<link rel="icon" type="image/svg+xml" href="/favicon.svg">
<link rel="alternate icon" href="/favicon.ico">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#ff8a01">
```
https://css-tricks.com/svg-favicons-and-all-the-fun-things-we-can-do-with-them/

**Comment by jantimon** [comment]
This plugin is only a wrapper around https://github.com/itgalaxy/favicons - maybe we can movew the discussion there?

**Comment by HansCronau** [comment]
See issue on https://github.com/itgalaxy/favicons:
https://github.com/itgalaxy/favicons/issues/304
