### ISSUE TITLE
SVG not working

### ISSUE THREAD

**Issue by ivands** [jantimon/favicons-webpack-plugin#200]
### The problem
Using a svg file will generate the following errors:
```
UnhandledPromiseRejectionWarning: Error: Input buffer has corrupt header: vips_realpath: unable to form filename
unix error: No such file or directory
glib: SVG has no elements
```

### Used packages
webpack v4.42.0
favicons-webpack-plugin v3.0.1
html-webpack-plugin v4.2.1

**Comment by jantimon** [comment]
The conversion from svg to image is done by  https://github.com/itgalaxy/favicons
Can you please try to ask that question there?

**Comment by duraz0rz** [comment]
@ivands If you haven't found a workaround, forcing `favicons` to version 6.1.0 fixes it for me.

**Comment by andrewplummer** [comment]
Having the same issue here... would love to see this resolved
