### ISSUE TITLE
Multiple Favicons Tutorial

### ISSUE THREAD

**Issue by JamesVanWaza** [jantimon/favicons-webpack-plugin#201]
I would like to know what would be the best way to show multiple favicons, should I rename them `logo`, `logo001`, `logo002`, `logo003`

```js
new FaviconsWebpackPlugin({
    logo: '/src/url/@0.5x.png',
    logo001: '/src/url/@1x.png',
    logo002: '/src/url/@2x.png',
    logo003: '/src/url/@4x.png',
})
```

**Comment by jantimon** [comment]
This is all done by the favicons library for you
