### ISSUE TITLE
Why remove emmitStast json?

### ISSUE THREAD

**Issue by maystrenkoYurii** [jantimon/favicons-webpack-plugin#202]
Emitt stats.json good feature in react ssr + ejs

**Comment by hadimostafapour** [comment]
I just created a fork of repo to handle this issue, `favicons-webpack-plugin-ssr` using following options:
```js
// derived from ssr extended to emit stats file
            path: resolve(directories.build, `${config.build.data}`),
            filename: 'icons.json',
```

I hope this option reverts back to the main repo.

**Comment by sibelius** [comment]
how does this works ?
