### ISSUE TITLE
Dependency error?

### ISSUE THREAD

**Issue by oivinds** [jantimon/favicons-webpack-plugin#203]
I checked jantimon/favicons-webpack-plugin repository for the out of date `mkdirp` and the deprecated `request` package, but its not there. 
So I am not sure how to deal with this warning:

`yarn add favicons-webpack-plugin -D
yarn add v1.22.4
[1/4] 🔍  Resolving packages...
warning favicons-webpack-plugin > favicons > to-ico > resize-img > jimp > mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning favicons-webpack-plugin > favicons > to-ico > resize-img > jimp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142`

**Comment by jantimon** [comment]
done in favicons-webpack-plugin 4.0.0
