### ISSUE TITLE
Exclamation point generate errors

### ISSUE THREAD

**Issue by pierredarrieutort** [jantimon/favicons-webpack-plugin#204]
When I use the `appDescription` property and write a sentence containing an exclamation point (like this : `Hello World !` the build crashes but when I remove `!` everything is okay. 🤔

**Comment by jantimon** [comment]
Do you have time to take a look what would cause this problem?

**Comment by vino46** [comment]
Hey there, I have got same issue. This advice helped me https://github.com/jantimon/favicons-webpack-plugin/issues/46#issuecomment-263069353

@pierredarrieutort you might to try doing this way either.

**Comment by jantimon** [comment]
good point @vino46 - any idea how we could fix this?

**Comment by vino46** [comment]
@jantimon honestly, I don't understand why exactly exclamation point breaks the build. But, I have some notes.

First of all, we can use a "LATIN LETTER RETROFLEX CLICK" as mentioned in issue above. Or any other exclamation point character described here https://en.wikipedia.org/wiki/Exclamation_mark#Unicode_and_HTML

Also I noticed, that this trouble appears only in `production` mode build. While running webpack build with `process.env.NODE_ENV !== 'production'` everything is fine. I have regular exclamation point both in title and description and no errors thrown.

**Comment by jantimon** [comment]
fixed in 5.0.0
