### ISSUE TITLE
Install fails on Node 14 [outdated dependencies]

### ISSUE THREAD

**Issue by Autapomorph** [jantimon/favicons-webpack-plugin#206]
`favicons-webpack-plugin@3.0.1` install fails on `Node 14` because of using outdated version of `favicons@5.5.0` which uses `sharp@0.23.3` which doesn't support `Node 14`

Current workarounds: use [yarn](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) or [npm-force-resolutions](https://github.com/rogeriochaves/npm-force-resolutions)

You can fix this issue by updating to `favicons@6.1.0`
BREAKING CHANGE: minimum supported Node.js version is `10.13.0`

**Comment by jantimon** [comment]
done in favicons-webpack-plugin 4.0.0
