### ISSUE TITLE
Generate only 1 favicon

### ISSUE THREAD

**Issue by fanchyfanch** [jantimon/favicons-webpack-plugin#208]
Despite the configuration of the "icons" property, webpack only generate one icon.

`icons           : {
                android     : true,
                appleIcon   : true,
                appleStartup: true,
                coast       : true,
                favicons    : true,
                firefox     : true,
                windows     : true,
                yandex      : true
            }`

@symfony/webpack-encore: 0.28.2
favicons-webpack-plugin: ^3.0.1

**Comment by walzm** [comment]
See #76, maybe the reason is you are running a dev build which may not create all files for performance reasons

**Comment by jantimon** [comment]
Exactly like @walzm said it is disabled during development for performance reasons - but this can be changed:

```
new FaviconsWebpackPlugin({
    logo: './src/logo.png', // svg works too
    devMode: 'webapp', // optional can be 'webapp' or 'light' - 'light' by default 
})
```
