### ISSUE TITLE
Append to <head>, not prepend

### ISSUE THREAD

**Issue by wallzero** [jantimon/favicons-webpack-plugin#21]
Currently, it seems the links are prepended inside the <head> tag. This is forcing my <meta charset="utf-8"> down, causing "the character encoding declaration of the HTML document was not found when prescanning the first 1024 bytes of the file" error in Firefox. Could the plugin please append after existing tags instead?

**Comment by thirdwaffle** [comment]
I believe this was fixed back in May: https://github.com/jantimon/favicons-webpack-plugin/commit/42bfc2877d5ac4302351d413c4131d32616da56d

Not sure when it was released to npm, but the version I'm using (v0.0.7) is injecting the icons to the end of the `head` tag.

**Comment by pdiniz13** [comment]
Is there a way to switch this and get them injected into the beginning of the head? Sometimes an analytics script takes too long too load and the favicon fails to load on chrome because it takes too long. I wanted to move this in front of that.

**Comment by jantimon** [comment]
Will be done with #184
