### ISSUE TITLE
Cannot find module './build/Release/sharp.node'

### ISSUE THREAD

**Issue by AlexGarrixen** [jantimon/favicons-webpack-plugin#210]
**webpack**- 4.43.0
**favicons-webpack-plugin** - 3.0.1
**html-webpack-plugin** - 4.3.0
**node** - v12.16.1
**npm** - 6.13.4

![Anotación 2020-06-21 104845](https://user-images.githubusercontent.com/60531551/85229221-21255e80-b3ae-11ea-8407-d3783bd29d9d.png)

**Comment by jantimon** [comment]
fixed with favicons-webpack-plugin - 4.0.0
