### ISSUE TITLE
Support for manifest files requiring basic auth

### ISSUE THREAD

**Issue by andrewplummer** [jantimon/favicons-webpack-plugin#212]
As detailed here:

https://github.com/koajs/basic-auth/issues/19

Chrome doesn't pass up basic auth when requesting manifest files.
The solution is to add `crossorigin` to the tag: `<link rel="manifest" href="manifest.json" crossorigin="use-credentials">`

Thanks!

**Comment by jantimon** [comment]
probably this should be done by the favicons plugin itself

**Comment by andrewplummer** [comment]
sounds good... shall I put in an issue?

**Comment by jantimon** [comment]
that would be nice 👍

**Comment by andrewplummer** [comment]
Actually looks like this option already exists...maybe it just needs to be configured? https://github.com/itgalaxy/favicons/pull/249

**Comment by andrewplummer** [comment]
Actually I guess the config can simply be passed through, however it would be a sensible default I think... this failure was difficult to track down... barring that then at least maybe a note about it in the documentation.

**Comment by jantimon** [comment]
Thanks for pointing that out - maybe we should add a information to the readme

would you like to open a or?
