### ISSUE TITLE
Bump dependency of favicons

### ISSUE THREAD

**Issue by Voltra** [jantimon/favicons-webpack-plugin#213]
Due to a major version change, and [new changes to the options](https://github.com/itgalaxy/favicons/pull/312), it would be nice to have a new version that includes the latest version of favicons.

**Comment by Voltra** [comment]
Update: It is available [as of v6.2.0](https://github.com/itgalaxy/favicons/issues/311#issuecomment-661823958)

**Comment by jantimon** [comment]
done in favicons-webpack-plugin 4.0.0

**Comment by Voltra** [comment]
Maybe use `^6.2.0` instead of a strict version number to allow for "transitive" updates post 6.2.0 ?

**Comment by jantimon** [comment]
done in favicons-webpack-plugin 4.3.0
