### ISSUE TITLE
 UnhandledPromiseRejectionWarning: Error: Unsupported MIME type: image/x-icon

### ISSUE THREAD

**Issue by yilmazbingo** [jantimon/favicons-webpack-plugin#218]
I use this package both in dev and prod environment. I have similar set up but I get this error in the production. it is fine in dev. 

here is the webpack set up

```
const FaviconsWebpackPlugin = require("favicons-webpack-plugin");
const pathToFavicon = path.join(__dirname, "../../favicon.ico");

plugins:[
    new FaviconsWebpackPlugin(pathToFavicon),

]
```
![Screenshot from 2020-07-30 22-23-27](https://user-images.githubusercontent.com/47233790/88993641-8117fa80-d2b4-11ea-9691-cee1eca923a6.png)

I m getting this error only in prod.

this is the webpack.dev vs webpack.prod

![Screenshot from 2020-07-30 22-25-38](https://user-images.githubusercontent.com/47233790/88993676-97be5180-d2b4-11ea-85f7-ab760f6f8a5f.png)

**Comment by jantimon** [comment]
Please use a `.png` file

**Comment by AnandaDwiprayoga** [comment]
i got same error, use a `.png` doesn't work

**Comment by MarcoLPR** [comment]
Same error here

**Comment by jantimon** [comment]
Png has the mime type `image/png` so I don't know how this might happen - could you please try to debug this error?

**Comment by yilmazbingo** [comment]
I tried to use this package for my another project, and got this error now:

Error: Unsupported MIME type: image/webp
![image](https://user-images.githubusercontent.com/47233790/103314751-e30a9680-49f1-11eb-84e2-779ed7ec4d24.png)

**Comment by kombojiec** [comment]
have everyone fixed this item?

**Comment by jantimon** [comment]
It's not a bug - the favicons library supports `.svg` and `.png`.  
Please convert your logos to one of those two formats.
