### ISSUE TITLE
Install failed (sharp)

### ISSUE THREAD

**Issue by foubei** [jantimon/favicons-webpack-plugin#219]
I upgraded to latest version of "favicons-webpack-plugin" and now can't "npm install"

`
make: Entering directory '/$user/node_modules/sharp/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  AR(target) Release/obj.target/../node-addon-api/nothing.a
  COPY Release/nothing.a
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
In file included from ../src/common.cc:23:0:
/usr/include/vips/vips8:35:10: fatal error: glib-object.h: No such file or directory
 #include <glib-object.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
sharp.target.mk:139: recipe for target 'Release/obj.target/sharp/src/common.o' failed
make: *** [Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory '/$user/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-42-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /$user/node_modules/sharp
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
`

node v12.18.3
npm v6.14.6
OS Ubuntu 18.04

**Comment by foubei** [comment]
Downgrading to "3.0.1" works perfectly as an alternative solution

**Comment by jantimon** [comment]
The problem is that `sharp` (a dependency of a dependency) is coupled with your node version and breaks a lot.

I hope that sharp will be stable soon

**Comment by jantimon** [comment]
favicons is now a peer dependency to help people picking a suitable version
