### ISSUE TITLE
Favicon is always emitted

### ISSUE THREAD

**Issue by Mrowa96** [jantimon/favicons-webpack-plugin#220]
I'm trying to optimize my webpack build and only problem left is with this plugin.
In **dev** mode with **watcher enabled**, favicon is always emitted, even if source file wasn't changed.

First run:
![image](https://user-images.githubusercontent.com/13927412/90386800-6223b180-e085-11ea-9242-c8ada5ca022d.png)

After change in some string:
![image](https://user-images.githubusercontent.com/13927412/90386787-5c2dd080-e085-11ea-8e13-c54cfee3c71b.png)

My plugin config:
```js
new FaviconsWebpackPlugin({
        logo: path.resolve(__dirname, 'src/static/images/logo.jpg'),
        inject: true,
        prefix: 'favicons/',
        favicons: {
            icons: {
                android: false,
                appleIcon: false,
                appleStartup: false,
                coast: false,
                favicons: true,
                firefox: false,
                windows: false,
                yandex: false,
            },
        },
}),
```
Node version: 13.11.0
Npm version: 6.13.7
Webpack version: 4.44.1
Plugin version: 4.2.0

**Comment by jantimon** [comment]
This is how webpack usually works..

**Comment by Mrowa96** [comment]
Well.. no. 
Look at the first picture in my comment above - index.html which is generated by HtmlWebpackPlugin is only emitted once, because during second compilation nothing changed in template for HtmlWebpackPlugin. 
Same rule applies to emitting svg and bundle with external js modules. Only FaviconsWebpackPlugin emits file which haven't changed.

**Comment by jantimon** [comment]
Yes this is causing bugs and will probably be fixed
