### ISSUE TITLE
Empty string as prefix causes incorrect url in development mode

### ISSUE THREAD

**Issue by StephanBijzitter** [jantimon/favicons-webpack-plugin#228]
When in production mode, the empty prefix `''` works correctly and creates a path like `/image.png`, but in development mode it creates `//image.png`, which in turn means `http(s)://image.png` and well, that doesn't really work.

The workaround is simple: `prefix: mode === 'production' ? '' : 'assets'`, but yeah, it is a bug.

Don't have much spare time this week, but maybe I'll be able to raise a pull request next week, if I can find the source, that is.

**Comment by jantimon** [comment]
That would be cool :)

**Comment by jantimon** [comment]
fixed in 5.0.0

**Comment by StephanBijzitter** [comment]
Well, turns out I completely forgot about this, thanks for picking it up!
