### ISSUE TITLE
Options to generate separate html files

### ISSUE THREAD

**Issue by benji07** [jantimon/favicons-webpack-plugin#229]
Hi, I'm looking for a way to use your plugin to generate a file that contains only the favicons and nothing more.

I'm stuck right now, because i don't know how to get rid of the css tags.

My configuration : 
```javascript
new HtmlWebpackPlugin({
    filename: '../../app/Resources/views/favicons/favicons.html.twig',
    templateContent: ({htmlWebpackPlugin}) => `${htmlWebpackPlugin.tags.headTags}`,
    inject: false,
}),
new FaviconsWebpackPlugin('./assets/images/barometre-logo.svg')
```

**Comment by jantimon** [comment]
Can you try:

```js
new HtmlWebpackPlugin({
    filename: '../../app/Resources/views/favicons/favicons.html.twig',
    templateContent: ({htmlWebpackPlugin}) => `${htmlWebpackPlugin.tags.headTags}`,
}),
new FaviconsWebpackPlugin({
  logo: './assets/images/barometre-logo.svg',
  inject: false,
})
```

**Comment by benji07** [comment]
With `inject: false` on the Favicons plugin i only have the css file (the opposite of what i want)

By looking at other issues in the HtmlWebpackPlugin i found something that work:

```javascript
templateContent: ({htmlWebpackPlugin}) => `${htmlWebpackPlugin.tags.headTags.filter((tag => tag.attributes['rel'] !== 'stylesheet'))}`,
```

but i don't know if it's the best way to do it

**Comment by jantimon** [comment]
Oh sorry now I understand what you mean :)

Right now there is only the solution which you proposed..  

Would it be possible to use https://github.com/itgalaxy/favicons directly without webpack?

**Comment by benji07** [comment]
sorry, it's not possible, i use webpack for building everything in my app, so i will use the solution i found

**Comment by jantimon** [comment]
the latest alpha adds a meta tag to identify favicon html tags easier
