### ISSUE TITLE
Error: w and h must be numbers (at Jimp.throwError ?)

### ISSUE THREAD

**Issue by lushfuture** [jantimon/favicons-webpack-plugin#23]
I'm getting this error trying to build with webpack. It seems to be happening sometime shortly after `favicons-webpack-plugin/lib/loader.js:96 -> generateIcons()` but I'm having trouble tracking it down.

```
Error: w and h must be numbers
    at Jimp.throwError (/Users/[user]/[project]/node_modules/jimp/index.js:82:43)
    at Jimp.contain (/Users/[user]/[project]/node_modules/jimp/index.js:1751:27)
    at Object.resize (/Users/[user]/[project]/node_modules/favicons/helpers-es5.js:221:27)
    at /Users/[user]/[project]/node_modules/favicons/es5.js:60:41
    at fn (/Users/[user]/[project]/node_modules/async/lib/async.js:746:34)
    at /Users/[user]/[project]/node_modules/async/lib/async.js:1213:16
    at /Users/[user]/[project]/node_modules/async/lib/async.js:166:37
    at /Users/[user]/[project]/node_modules/async/lib/async.js:706:43
    at /Users/[user]/[project]/node_modules/async/lib/async.js:167:37
    at Jimp.<anonymous> (/Users/[user]/[project]/node_modules/async/lib/async.js:1209:30)
    at /Users/[user]/[project]/node_modules/jimp/index.js:289:27
    at .<anonymous> (/Users/[user]/[project]/node_modules/pngjs/lib/png.js:74:7)
    at g (events.js:286:16)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at .<anonymous> (/Users/[user]/[project]/node_modules/pngjs/lib/png.js:36:10)
  ```

Tried with nodejs 6.2 & 6.4.

My webpack config isn't doing anything crazy -

```js
{
...
plugins: [
    new FaviconsWebpackPlugin(PATHS.favicon),
    new HtmlWebpackPlugin({
      title: "Project A"
    }),
  ]
...
}
```

Funny thing is I wrote this project on another machine (also a Macbook running same dev environment) and only having this problem when I tried building on my other Macbook. I can't identify any differences between the two that might be causing something like this to happen. I'm obviously missing something.

Any insight into what might be causing this? Thanks.

**Comment by jantimon** [comment]
That seems to be a favicons issue: https://github.com/haydenbleasel/favicons

**Comment by CapitalCloud** [comment]
and i edit the file node_modules/favicons-webpack-plugin/lib/loader.js

var favicons = require('favicons/es5'); to var favicons = require('favicons');

this error was gone!

anything help?

**Comment by jantimon** [comment]
Can't be fixed here - please ask the  https://github.com/haydenbleasel/favicons to fix the es5 version.

**Comment by thenano** [comment]
note: downgrading favicons dependency to 4.7.7 also resolves the issue. Could it be an api change for favicons that is causing the issue? Maybe lock down the version dependency in this package?

**Comment by jantimon** [comment]
@thenano Cool nice hint! 👍 
https://github.com/haydenbleasel/favicons/issues/147
@haydenbleasel do you know why 4.7.7 is causing this?

**Comment by lushfuture** [comment]
Thanks guys, I just downgraded the package to 4.7.7 to resolve the issue as @thenano suggested and everything is a-ok 👍 

@CapitalCloud good catch this is interesting.

I see [haydenbleasel/favicons#147 ](https://github.com/haydenbleasel/favicons/issues/147) is open now so lets close this!

**Comment by haydenbleasel** [comment]
Yo yo. Yeah I'll get through this open issue ASAP and hopefully it'll resolve this.
