### ISSUE TITLE
Inject different favicons in different html files

### ISSUE THREAD

**Issue by jripmeester** [jantimon/favicons-webpack-plugin#237]
Is it possible to inject different favicons in different HTML files. I've got the inject of this going. But the plugin only seems to generate 1 favicon. In the example below only the last include of this plugin generates the icon (thuislink one). The other one (weckx one) isn't in the dist folder.

Am i missing something of is it just not possible? Thanks!

This is my current config:

new HtmlWebpackPlugin({
                inject: false,
                excludeChunks: ['app'],
                filename: 'webapp_weckx.html',
                templateContent: ({htmlWebpackPlugin}) => `
                    ${htmlWebpackPlugin.tags.headTags}
                `,
            }),
            new HtmlWebpackPlugin({
                inject: false,
                excludeChunks: ['app'],
                filename: 'webapp_thuislink.html',
                templateContent: ({htmlWebpackPlugin}) => `
                    ${htmlWebpackPlugin.tags.headTags}
                `,
            }),
            new FaviconsWebpackPlugin({
                logo: settings.favicons.weckx.logo,
                prefix: settings.favicons.weckx.prefix,
                cache: false,
                inject: htmlPlugin => basename(htmlPlugin.options.filename) === 'webapp_weckx.html',
                favicons: {
                    appName: pkg.name,
                    appDescription: pkg.description,
                    developerName: pkg.author.name,
                    developerURL: pkg.author.url,
                    path: settings.paths.dist,
                }
            }),
            new FaviconsWebpackPlugin({
                logo: settings.favicons.thuislink.logo,
                prefix: settings.favicons.thuislink.prefix,
                cache: false,
                inject: htmlPlugin => basename(htmlPlugin.options.filename) === 'webapp_thuislink.html',
                favicons: {
                    appName: pkg.name,
                    appDescription: pkg.description,
                    developerName: pkg.author.name,
                    developerURL: pkg.author.url,
                    path: settings.paths.dist,
                }
            })

**Comment by jantimon** [comment]
yes that's possible 👍

**Comment by jripmeester** [comment]
@jantimon We'll it's not working with this config. What am i missing here?

**Comment by jantimon** [comment]
Here is a working example:

https://codesandbox.io/s/favicons-webpack-plugin-demo-multiple-favicons-l9x4p
