### ISSUE TITLE
what happened to emitStats and statsFilename features?

### ISSUE THREAD

**Issue by Fxlr8** [jantimon/favicons-webpack-plugin#238]
Hi, I just updated my dependencies and found out that these features do not work any more. I couldn't find anything about them being deprecated in the changelog. Did you just remove them silently?

Anyways, how can I get the stats file now? That was a very useful feature in my case.

**Comment by Fxlr8** [comment]
found that sneaky commit https://github.com/jantimon/favicons-webpack-plugin/commit/e97f580e66b780a1b4dbe552829474cea87f020f

but why, tho?

**Comment by jantimon** [comment]
why do you need these stats files?

**Comment by Fxlr8** [comment]
I deploy my app to the CloudFlare worker and I use the stats file to inject all the tags into my index.html file.

**Comment by jantimon** [comment]
Would it be possible to use the html-webpack-plugin for you?
