### ISSUE TITLE
Add support for maskable icons

### ISSUE THREAD

**Issue by andyrichardson** [jantimon/favicons-webpack-plugin#242]
## About

Hey there, first off, thanks for the awesome plugin!

It would be great if there was support for [maskable icons](https://web.dev/maskable-icon/).

## Proposal

Add an opt-in option for using maskable icons

```tsx
new FaviconsWebpackPlugin({
  logo: './src/logo.png',
  maskable: true
});
```

Resulting output in manifest

```js
{
  "src": "path/to/maskable_icon.png",
  "sizes": "196x196",
  "type": "image/png",
  "purpose": "maskable" // <-- New property value `"maskable"`
},
```

**Comment by uwolfer** [comment]
See https://github.com/itgalaxy/favicons/pull/323.

**Comment by andyrichardson** [comment]
Thanks - sounds like this is outside the scope of this project
