### ISSUE TITLE
cache-loader requires Webpack 4

### ISSUE THREAD

**Issue by 321ckatz123** [jantimon/favicons-webpack-plugin#249]
This library has a dependency on cache-loader, but that has been deprecated (see https://github.com/webpack-contrib/cache-loader), as well as depends on Webpack 4, so the new v5 push made today complains about dependency warnings when using Webpack 5.

That all said, I can't see where this library is actually requiring it? Is this just a simple remove the dead dependency? I can create a simple PR that does that, if so desired.

**Comment by jantimon** [comment]
hey @321ckatz123 thank you so much for letting me know!

you are absolutely right - cache-loader was removed from the code but is still a dependency and doesn't belong there any longer...
I'll publish a new version with a fix

**Comment by jantimon** [comment]
Added a pr here: #250

**Comment by 321ckatz123** [comment]
@jantimon Sounds good. Thanks! Saw this prompted some other cleanup as well in the PR, so good news all around 💯

**Comment by jantimon** [comment]
released as 5.0.1
