### ISSUE TITLE
Message: generate only a single favicon for fast compilation time in development mode

### ISSUE THREAD

**Issue by tmcconechy** [jantimon/favicons-webpack-plugin#252]
We recently updated to `"favicons-webpack-plugin": "^5.0.1",` now when building with this config:

```
  module.exports.plugins.push(new FaviconsWebpackPlugin('app/assets/favicon.ico');
```

But now i get this error :
```
LOG from favicons-webpack-plugin
<i> generate only a single favicon for fast compilation time in development mode. This behaviour can be changed by setting the favicon mode option.
```

How do i get rid of the error? Or is it just warning thats now always there (maybe consider removing?). I tried this and different modes but still getting it

```
  module.exports.plugins.push(new FaviconsWebpackPlugin('app/assets/favicon.ico', {
    mode: 'light', // optional can be 'webapp', 'light' or 'auto' - 'auto' by default
    devMode: 'light'
  }));
  ```

**Comment by jantimon** [comment]
Why do you think it's an error?

It's only a log - logs can be globally disabled by setting the webpack logging level.

The code which adds the log is here:

https://github.com/jantimon/favicons-webpack-plugin/blob/e4946bf74d6f212b7a93583cdc3819693b966bd2/src/index.js#L297-L300

As you can see it is only shown if no mode was set explicitly.

The following config should hide the message:

```js
new FaviconsWebpackPlugin({
   logo: 'app/assets/favicon.ico',
   mode: 'auto'
})
```

**Comment by tmcconechy** [comment]
Thanks that 100% worked. I was setting the options wrong.
