### ISSUE TITLE
Used packages require unsafe package url-regex

### ISSUE THREAD

**Issue by Supportic** [jantimon/favicons-webpack-plugin#253]
I like really this plugin, but after installing it states that the package favicon is using packages and one of them is using url-regex which is considered as unsafe.
Path: favicons > to-ico > resize-img > jimp > url-regex
https://www.npmjs.com/advisories/1550

After looking into it, it seems like [resize-img](https://github.com/kevva/resize-img/blob/master/package.json#L33) is using an old version of [jimp](https://github.com/oliver-moran/jimp/blob/master/package.json#L28) which is not using url-regex anymore. [[ref](https://github.com/oliver-moran/jimp/issues/926#issuecomment-676042128)]

Can I manually upgrade the versions without destroying the build?
Surprisingly I cannot find any mentions of url-regex in any jimp folder of node_modules.

**Comment by jantimon** [comment]
I wrote a mail to the resize-image author - maybe he will take a look 🤞

If not you might sponsor him to upgrade his package 

If you have any idea what can be done on my side let me know
