### ISSUE TITLE
Add filename pattern option to allow using contenthash in filenames

### ISSUE THREAD

**Issue by jbbr** [jantimon/favicons-webpack-plugin#254]
Since 5.0.0 it's possible to add `[contenthash]` etc. to the publicPath.
This allows creation of urls like this:
```
myweb.tld/assets/[contenthash]/manifest.json`
```
But this also means that regardless of which file generated by this plugin changed, the hash always changes for all files.
Meaning even unchanged files have to be refetched to be cached.

Webpack itself provides filename patterns to allow for file-specific cache busting. 
E.g:
```js
output: {
  filename: '[name].[contenthash].bundle.js',
  ...
}
```
It would be great if this could be somehow archived with this plugin as well.

e.g add options for file name generation:

```js
new MiniCssExtractPlugin({
  filenamePattern: '[name].[contenthash].[ext]'
})
```
this would cover all generated filetypes (manifest, images, ...) with a single option.

Related issues:
#240

**Comment by jantimon** [comment]
You can do this with `prefix: 'assets/[contenthash]/`

**Comment by leevigraham** [comment]
> You can do this with prefix: 'assets/[contenthash]/'

This results in the same issue as @jthomaschewski mentioned:

> But this also means that regardless of which file generated by this plugin changed, the hash always changes for all files.
Meaning even unchanged files have to be refetched to be cached.

I believe what @jthomaschewski wanted was to have the files written using a file pattern:

```assets/[name].[contenthash].[ext]```

**Comment by jthomaschewski** [comment]
Oh sorry, I missed the answer @jantimon.
What I wanted to achieve is exactly what @leevigraham pointed out.

**Comment by PeterKottas** [comment]
I think this should be reopened or am I missing something?

**Comment by shaselboeck** [comment]
I would be happy about this adaptation too

**Comment by Aaronius** [comment]
Same here. I feel like this should be reopened.
