### ISSUE TITLE
favicon dependency 1 minor version behind

### ISSUE THREAD

**Issue by nicovanniekerk** [jantimon/favicons-webpack-plugin#256]
Hi, i am busy working on upgrading my environment to the latest TLS version of node 14.15, over that requires 'sharp' to be on version > 26.1, the version of the Favicon package that is currently required for this library is on version '6.2.0' which in turn requires sharp on version '0.25.2'. this version of sharp does not support NodeJS higher that version 12, it only updated on version 26 of the sharp module. Due to this version of sharp being behind results in me being unable to upgrade my environment which in turn leaves my entire stack vulnerable.

Can the favicon dependency for this package please be update to '26.1' this new version of the Favicon package already depends on the correct version of its 'sharp' dependency.
The following link shows the correct sharp version on the new version of favicon, Please update to the new version.
https://github.com/itgalaxy/favicons/blob/1803444baa1c6b4093aa64a5fe69210ae03cb638/package.json#L57

**Comment by jantimon** [comment]
favicons-webpack-plugin 5 has no longer a direct dependency on favicons but a peer dependency to solve exactly this issue

which version of the favicons-webpack-plugin do you use?

**Comment by nicovanniekerk** [comment]
Hi @jantimon Thanks for reaching out so quick, i would like to use the latest version. which is the one i used to track the version of sharp that is being in stalled and failing on the new versions of NodeJS.

**Comment by jantimon** [comment]
What can I do to help you here?

Can't you just do sth like:

```
npm i favicons@6.2.1
```

**Comment by nicovanniekerk** [comment]
Hi, all i need is this, ' "favicons": ">= 6.2.0"' to change to this in a new version of your plugin, ' "favicons": ">= 6.2.1"' can not override the install as the original just fails and breaks my build process completely, i am sure this will be an issue for more people than just me pretty soon.

**Comment by jantimon** [comment]
Sorry but that doesn't make sense to me.

`"favicons": ">= 6.2.0" ` allows you to install 6.2.1

please remove your lock files and run `npm install favicons@6.2.1`

**Comment by nicovanniekerk** [comment]
Thanks, just for future note to someone making the same noob mistake as me :) there was also an old cached version i had to trash, but this does work now thanks.

**Comment by jantimon** [comment]
Cool 👍
