### ISSUE TITLE
File regenerated on every build with persistentCache:true

### ISSUE THREAD

**Issue by softcraft-development** [jantimon/favicons-webpack-plugin#26]
My config:

```
new FaviconsWebpackPlugin({
    logo: './path/to/logo.png',
    prefix: "path/to/output/dir/",
    emitStats: true,
    statsFilename: 'iconstats-[hash].json',
    persistentCache: true,
    background: '#fff',
    title: 'My Title'
})
```

In `path/to/output/dir`, I see a `.cache` file, and it contains `hash` and `outputHash`, suggesting that `persistentCache: true` is functioning correctly. However, the output files are always regenerated on every webpack build, even when my logo file doesn't change. The `hash` and `outputHash` values don't appear to change between builds.

**Comment by softcraft-development** [comment]
I have a PR that fixes this, at least for my situation: https://github.com/jantimon/favicons-webpack-plugin/pull/27

**Comment by jantimon** [comment]
Right now I am looking for a ways to get rid of the cache feature (and replace it with a module which focuses on caching like https://github.com/mzgoddard/hard-source-webpack-plugin )

**Comment by damianobarbati** [comment]
Any news on this?
