### ISSUE TITLE
Cannot destructure property `tagName` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by in-in** [jantimon/favicons-webpack-plugin#260]
## Current behaviour 💣

I get the error when I build my project
```sh
TypeError: Cannot destructure property `tagName` of 'undefined' or 'null'  
```
![210541614095064](https://user-images.githubusercontent.com/8797432/108868387-37ec1700-7607-11eb-8569-01b5eac5e45e.png)

## Expected behaviour ☀️

It should be built without any errors.

I want to fine-tune which icons to use in the project.
```json
favicons: [
  "favicon-16x16.png",
  "favicon.ico"
]
```
But it doesn't work if I remove the default elements from the array. Or it only works with the `inject: false` option.

### Reproduction Example 👾

https://codesandbox.io/s/tender-jones-obesr?file=/webpack.config.js

## Environment 🖥

```sh
Node.js v10.23.0
linux 5.4.0-40-generic
```

```sh
+-- favicons@6.2.1
+-- favicons-webpack-plugin@5.0.1
| `-- html-webpack-plugin@5.2.0  deduped
+-- html-webpack-plugin@5.2.0
+-- webpack@5.24.0
`-- webpack-cli@4.5.0
```

**Comment by jantimon** [comment]
Oh favicons generates the following html tags:

```
[
  '<link rel="shortcut icon" href="favicon.ico">',
  '<link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">',
  '',
  '',
  '<link rel="manifest" href="manifest.json">',
  '<meta name="mobile-web-app-capable" content="yes">',
  '<meta name="theme-color" content="#fff">',
  '<meta name="application-name" content="favicon">'
]
```

so I guess it's a bug on their side to generate empty strings...  
but it would be easy to add a small filter :)

**Comment by jantimon** [comment]
Thanks a lot for reporting the issue

I'll release the fix from #261 soon :)  

Maybe you can ask in the favicons repository why it generates empty strings in the tags array.

**Comment by jantimon** [comment]
Released in `favicons-webpack-plugin@5.0.2`

**Comment by code1x1** [comment]
could you backport the bugfix to favicons-webpack-plugin@4

**Comment by tomasztomys** [comment]
please backport the bugfix also for 4.0
