### ISSUE TITLE
Logo glob pattern

### ISSUE THREAD

**Issue by tscpp** [jantimon/favicons-webpack-plugin#263]
**Is your feature request related to a problem? Please describe.**
I writing a startpoint generator and I don't know what file extension is used for the logo.

**Describe the solution you'd like**
Having a glob pattern to the logo like so:
```js
new FaviconsWebpackPlugin({
    logo: 'public/icon.*'
})
```

**Describe alternatives you've considered**
Option to auto resolve file extension to logo.
```js
new FaviconsWebpackPlugin({
    logo:  {
        src: 'public/icon',
        resolveExtension: true
    }
})
```

**Comment by jantimon** [comment]
By default it picks up `logo.png` in the root folder (as this is also the default logo location for gitlab sourcetree and other tools) maybe we could extend it to also look for `logo.svg`
