### ISSUE TITLE
[Feature Request] Allow custom filename (manifest.json -> custom.webmanifest)

### ISSUE THREAD

**Issue by latipun7** [jantimon/favicons-webpack-plugin#272]
**Is your feature request related to a problem? Please describe.**
Current outputted filename `manifest.json` is not a standard file extension for webmanifest. [Correct manifest extension](https://webhint.io/docs/user-guide/hints/hint-manifest-file-extension) is `.webmanifest`

**Describe the solution you'd like**
Allow custom filename in the configuration.
```js
plugins: [
  new FaviconsWebpackPlugin({
    // Custom manifest filename (default: manifest.json)
    filename: 'mysite.webmanifest',
  })
]
```

**Describe alternatives you've considered**
Rename `manifest.json` in index file to `site.webmanifest`.

**Additional context**
![issue](https://i.imgur.com/LIJZkED.png)

**Comment by devlegacy** [comment]
An alternative could be to create hook

```js
compiler.hooks.thisCompilation.tap('FaviconsWebpackPlugin', compilation => {

      compilation.hooks.processAssets.tapPromise(
        {
          name: 'FaviconsWebpackPlugin',
          stage: Compilation.PROCESS_ASSETS_STAGE_ADDITIONS
        },
        async () => {
          // console.log('compilation',compilation)
          const faviconCompilation = faviconCompilations.get(compilation);
          if (!faviconCompilation) {
            return;
          }
          const faviconAssets = (await faviconCompilation).assets;

         // here we can alter the output - start hook (?)
          for(const asset of faviconAssets) {
            if(asset.name === 'manifest.json') {
              asset.name = 'manifest.webmanifest'
              faviconAssets.push(asset)
              break
            }
          }
         // here we can alter the output - end hook (?)

          faviconAssets.forEach(({ name, contents }) => {
            compilation.emitAsset(name, contents);
          });
        }
      );
    });
```

**Comment by bencresty** [comment]
+1

In projects webpack here uses a rename plugin to rename the file after build, but it would be better if we could just directly set the right name.

Isn't `manifest.webmanifest` a better default name too or is there still something around that uses `manifest.json`?

**Comment by latipun7** [comment]
Still relevant ig
