### ISSUE TITLE
Manifest cannot be loaded if credentials are required

### ISSUE THREAD

**Issue by ZLJasonG** [jantimon/favicons-webpack-plugin#276]
There doesn't appear to be any option to specify if the crossorigin="use-credentials" should be added to the generated manifest.json link.

As per https://web.dev/add-manifest/#link-manifest this is required to enable cookies to be sent with the manifest request

**Comment by jantimon** [comment]
You can use the `favicons` option to configure the underlying favicons npm package
https://www.npmjs.com/package/favicons

it provides the `loadManifestWithCredentials` option

please let me know if this helps :)

**Comment by ZLJasonG** [comment]
Excellent thanks, that's done the trick. I had just seen the code in generateFaviconsLight and figured it was completely unsupported.
