### ISSUE TITLE
[Feature Request] - Ability to disable output of manifest.json

### ISSUE THREAD

**Issue by oller** [jantimon/favicons-webpack-plugin#277]
**Is your feature request related to a problem? Please describe.**
We're using this plugin to generate favicons, but another more verbose manifest related webpack plugin to build out our manifest.  Webpack 5 currently errors about 2 outputs to the same name.  

I see you've an option to pass in a manifest template, but as our other manifest plugin generates the manifest at build time, we have nothing meaningful to pass in here.

**Describe the solution you'd like**
A `manifest: false` option to disable the output of the manifest, whilst leaving all the other image generation functionality as is.

**Describe alternatives you've considered**
Passing in a template to `manifest` but, as our other plugin generates this at build time and references a lot of vars we want injected into the manifest, that doesn't seem to achieve what we're looking for.

**Additional context**

**Comment by andy128k** [comment]
This feature is already implemented in upcoming `favicons` 7.0.0 with [a new `output` option](https://github.com/itgalaxy/favicons/pull/348).
