### ISSUE TITLE
With webpack2 it stops build from completing 

### ISSUE THREAD

**Issue by MikaAK** [jantimon/favicons-webpack-plugin#29]
When using this plugin with webpack2 it stops the build from completing and it just ends up hanging indefinitely. Removing this plugin solves this problem

**Comment by jantimon** [comment]
Hmm do you have any idea why?

**Comment by MikaAK** [comment]
No clue unfortunately, it just stops, I don't know the internals of this plugin well enough to say either :(

**Comment by RobNielsen515** [comment]
I'm having the same issue with webpack 1.13.0. Removing the plugin resolves the issue as reported above.

I added the debug-webpack-plugin to my project to see if I could gain any insight. 

`$ npm run dev-server

> NODE_ENV=development webpack-dev-server

Building development version.
clean-webpack-plugin: /Users/rob/src/xxx has been removed.
  webpack:compiler:after-plugins  +0ms
  webpack:compiler:after-resolvers  +1ms
  webpack:compiler:watch-run  +10ms
  webpack:compiler:normal-module-factory  +1ms
  webpack:compiler:context-module-factory  +0ms
  webpack:compiler:compile  +0ms
  webpack:compiler:compilation  +2ms
  webpack:compiler:make  +4ms
  webpack:compiler:normal-module-factory  +1ms
  webpack:compiler:context-module-factory  +1ms
  webpack:compiler:compilation  +1ms
  webpack:compiler:normal-module-factory  +11ms
  webpack:compiler:context-module-factory  +0ms
  webpack:compiler:compilation  +2ms
 http://0.0.0.0:8000/webpack-dev-server/
webpack result is served from /
content is served from /Users/rob/src/xxx
404s will fallback to /index.html
  webpack:compiler:failed  +45ms
  webpack:compiler:after-compile  +2s
`
So it looks like compilation failed but no message was emitted and webpack just hangs.

**Comment by Inoir** [comment]
Having same issue. Changing the path didnt help me.
Im using webpack2 and do net get any errors.

**Comment by RobNielsen515** [comment]
Some additional info. I upgraded some node modules today and I ran into the problem again. I upgraded to node 6.2.1 (Mac) and the problem went away.

**Comment by kevin-miles** [comment]
@Inoir @RobNielsen515 @MikaAK @jantimon 

hi, i had issues with favicons-webpack-plugin locking up the build and i believe i found the root cause + solution.

I was running into an issue locally with node v4.4.5: 

> ModuleBuildError: Module build failed: TypeError: Buffer.alloc is not a function

This occurs in /node_modules/to-ico/index.js:15:21.
**Reason:** Buffer API is only available in v5.10.0+.

**Fix:** use a node version manager such as NVM and upgrade to v5.10.0+

**Comment by jantimon** [comment]
@kevin-miles that's a nice find - and kind of sad that the npm registry is so complicated to use.. why can't they back transpile it on registry level?

**Comment by felipeleusin** [comment]
you can add in your package.json { "engines" : { "node" : ">=5.10.0" } } that will trigger warning when people install the package
