### ISSUE TITLE
is it possible to change "apple-mobile-web-app-status-bar-style" value ?

### ISSUE THREAD

**Issue by jasan-s** [jantimon/favicons-webpack-plugin#30]
The reason i ask is because , when i launch my app from homescreen the appbar text is white and my app background is also white. so the only thing visible is the battery icon. Additionally, if apple-mobile-web-app-capable value can be changed as well?

**Comment by skizzo** [comment]
+1

**Comment by joshporter1** [comment]
+1, couldn't see where this was being set in the codebase but I'm willing to help make this an option.

**Comment by joshporter1** [comment]
Looking like the problem is in the favicons dependency. See [here](https://github.com/evilebottnawi/favicons/issues/157)

**Comment by FlorinDavid** [comment]
+1 it will be just great to support this meta tag
Thank you!

**Comment by invalidred** [comment]
+1 it would be great to support this meta tag configuration. Is there a way to override it for now?

**Comment by invalidred** [comment]
For anyone who stumbles upon this issue, please checkout out [apple-status-bar-style-webpack-plugin](https://www.npmjs.com/package/apple-status-bar-style-webpack-plugin) npm.

**Comment by skizzo** [comment]
Looks like a deadlink, invalidred..

**Comment by invalidred** [comment]
@skizzo sorry but i had an issue with npm publish, and now they've told me i need to wait for 24 hours before i can republish. I will update this post as soon as i can publish it.

**Comment by invalidred** [comment]
@skizzo try again, it should be available. Apologies for any inconvenience caused.
