### ISSUE TITLE
get the error - TypeError: favicons is not a function

### ISSUE THREAD

**Issue by newbie78** [jantimon/favicons-webpack-plugin#309]
i'm use last version of package
    "favicons": "^7.0.0-beta.4",
    "favicons-webpack-plugin": "^5.0.2"

but when i'm build my project, i'm get an error.

fixed by adding this:
![image](https://user-images.githubusercontent.com/28735/170388435-ab5dc474-b0fb-4bff-b005-b3f7c959be09.png)

please add to master

**Comment by rmhdev** [comment]
Looks like it's related to the beta version of `favicons` (see #302). In my case I was able to fix this issue by installing v6:

```shell
npm install --save-dev favicons@^6.2.2
```

Or in yarn:
```shell
yarn add --dev favicons@^6.2.2
```

**Comment by ximex** [comment]
not favicons v7 stable is released. pls make this lib compatible with it.
https://github.com/itgalaxy/favicons/releases/tag/v7.0.0

**Comment by PavleNeskovic** [comment]
Until this lib is updated, setting favicons to v6.2.2 fixes the issue.
