### ISSUE TITLE
Adjust filename URLs

### ISSUE THREAD

**Issue by beckend** [jantimon/favicons-webpack-plugin#31]
I use react router, and if my visit my route it tries to access the favicons below route:
`/myroute/mysubroute/file.png`.
But if course the files are in the root...the webpack entries file correctly obeys `publicPath`option, prefixing all paths with publicPath.

**Comment by jantimon** [comment]
What about setting a base path?

**Comment by beckend** [comment]
That would of course work but is about to be deprecated in `history` module, the recommended way to change a basename in history module/react-router is to change it in the module [basename history](https://github.com/reactjs/react-router/blob/master/docs/guides/Histories.md).
