### ISSUE TITLE
Handling a few different image files as favicon and touch icon

### ISSUE THREAD

**Issue by Ievgen-Lebediev** [jantimon/favicons-webpack-plugin#311]
**Is your feature request related to a problem? Please describe.**

My application needs to handle two different *.png files (two different images not only different sizes) for favicon and for touch icons.
I did not find the solution for my issue based on the api mentioned at the github pages (both on favicons-webpack-plugin and favicons repos).

**Current configuration**

```
new faviconsWebpackPlugin({
    logo: "./src/images/favicon.png",
    cache: true,
    inject: true,
   favicons: {
      appleStatusBarStyle: 'default',
      icons: {
        "android": [
          "./src/images/logo.png",
        ],
        "appleIcon": [
          "./src/images/logo.png",
        ],
        "favicon": [
          "./src/images/favicon.png",
        ]
      }
    }
})
```
**Output**

All icons are derived from one source ` logo: "./src/images/favicon.png"`  without taking into account sources identified in the `icon` property.

**Describe the solution you'd like**

Is there some way to handle a few differnet images as favicons and touch icons?

**Comment by anilanar** [comment]
Does the example make sense though? What happens to the web manifest?  Just create two and ignore one of them? Feels dirty.
