### ISSUE TITLE
[hash] in publicPath does not get replaced

### ISSUE THREAD

**Issue by chrillo** [jantimon/favicons-webpack-plugin#34]
I have the following web pack config, since I am deploying to a CDN I want each new build to go in a new directory named with the build hash. when I create a new build I end up with the following path for the icons

```
...
output = {
        publicPath: '[hash]/', // Set the public path to the current build hash
        path: 'public/' + ENV + '/[hash]/',  
        filename: '[name].js',  
        chunkFilename: '[id].js'
 } // full file attached
...
```

`
<link rel="apple-touch-icon" sizes="57x57" href="[hash]/icons-48ad63d7546929887bb2a3c1a9cac2fc/apple-touch-icon-57x57.png">`
// the childCompilation hash gets applied correctly, but the **main hash does not**

I used to have the same problem with the html webpack plugin, I tried to apply the same solution that fixed it for the html webpack plugin https://github.com/ampedandwired/html-webpack-plugin/commit/41a255a2f1a0be054b03ceb9231f538ffbf350af but I could not get it to work, I always got stuck with this error Path variable [hash] not implemented in this context: [hash]/ , doing some console log revealed that the compilation object does not have a hash at the point where the favicon plugin does something with the public path, Line 11 in compiler.js & Line 40 in favicon.js. Any suggestions on how to fix this?

[webpack.config.js.zip](https://github.com/jantimon/favicons-webpack-plugin/files/476729/webpack.config.js.zip)

**Comment by jantimon** [comment]
fixed in 5.0.0
