### ISSUE TITLE
Question: how to generate favicons only head tags, nothing else

### ISSUE THREAD

**Issue by bertoost** [jantimon/favicons-webpack-plugin#346]
Hi there,

I am able to generate the favicons and with the html plugin there is a template generated with all favicon tags. But with a couple of more and I only want a file with the favicons and nothing else. Is that possible?

Regards, Bert

**Comment by andy128k** [comment]
It is not possible now.

There was a similar request already (#298).

**Comment by bertoost** [comment]
Cool! Thanks. I will follow that, this can be closed
