### ISSUE TITLE
Upgrade to `favicons` 7.1.5

### ISSUE THREAD

**Issue by xavierfoucrier** [jantimon/favicons-webpack-plugin#357]
Thanks for this great package 🎉

Unfortunately, since version 0.33.0, sharp team has changed the way the library is installed. When using sharp side by side with this package there are conflicts. The package `sharp` is not part of this webpack plugin, but is part of the `favicons` package you are using, which have been updated recently!

> See https://github.com/itgalaxy/favicons/issues/446.

**Comment by andy128k** [comment]
`favicon` version is not pinned (it's just `^7`). You may just upgrade it and no changes in `favicons-webpack-plugin` is needed.

**Comment by xavierfoucrier** [comment]
Hello 👋 

I missed that in the `package.json`, sorry!
Thanks for the fast answer 🚀 😎 

Closing the issue.
