### ISSUE TITLE
Generated Images are flipped

### ISSUE THREAD

**Issue by pixelize** [jantimon/favicons-webpack-plugin#38]
Hi there,

I just saw some of my generated icons files are flipped but also has a line on the left side. My source file is a square image.

See example images : 
- apple-touch-startup-image-1496x2048.png
  ![apple-touch-startup-image-1496x2048](https://cloud.githubusercontent.com/assets/2931627/19316179/b72d70e6-90a0-11e6-94a2-7b465c9c46bf.png)
- apple-touch-startup-image-1182x2208.png
  ![apple-touch-startup-image-1182x2208](https://cloud.githubusercontent.com/assets/2931627/19316183/b9c3e1e6-90a0-11e6-92f4-8b14a88f32d9.png)
- apple-touch-startup-image-748x1024.png
  ![apple-touch-startup-image-748x1024](https://cloud.githubusercontent.com/assets/2931627/19316185/bbfc9af2-90a0-11e6-893a-9c908a117b97.png)

Do you also encounter this bug ?
favicons 4.8.3
node v6.2.1

Thanks for helping

**Comment by jantimon** [comment]
Looks like this is a favicons bug :)
