### ISSUE TITLE
Support Promise or function with callback for source `logo` option 

### ISSUE THREAD

**Issue by evilebottnawi** [jantimon/favicons-webpack-plugin#42]

**Comment by jantimon** [comment]
don't see a reason for that but as https://github.com/jantimon/favicons-webpack-plugin/blob/master/lib/compiler.js#L5 is async it would be very easy to implement.

would you like to create a pull request?

**Comment by evilebottnawi** [comment]
@jantimon I do not know much api `webpack` :sob: I would love to see an example of how it is implemented
