### ISSUE TITLE
Broken tests

### ISSUE THREAD

**Issue by lucassus** [jantimon/favicons-webpack-plugin#43]
Since this commit https://github.com/webpack/webpack/commit/2596b329b6da4ca8189b40504625261c704221ee webpack uses different footer for generated files. It causes size mismatch in the comparator `const compareOptions = {compareSize: true};`

**Comment by lucassus** [comment]
Other tests are failing because of `"favicons": "^4.7.1"` The latest version `4.8.x` generated icons with more sizes

**Comment by jantimon** [comment]
Thanks for investigating 👍

**Comment by lucassus** [comment]
Fixed in #44
