### ISSUE TITLE
Exclamation mark in title

### ISSUE THREAD

**Issue by CloudMax94** [jantimon/favicons-webpack-plugin#46]
It is currently not possible to have an exclamation mark in the title.
I didn't spend much time trying to figure out why, but I assume it is because of [this](https://github.com/jantimon/favicons-webpack-plugin/blob/74c602b650f5e542fa078582ec87d7cc9e6125f9/lib/compiler.js#L19-L26).

My application is named "osu!stats" so not being able to use an exclamation mark is kind of a big problem for me.

**Comment by jantimon** [comment]
You are probably right - unfortunately I don't know how to escape exclamation marks in webpack loaders :(

**Comment by oliverturner** [comment]
@CloudMax94 You could try using a unicode substitute? 

Try running "ǃ" === "!" in the console and it'll return false
