### ISSUE TITLE
Seems it doesn't work with WebpackDevMiddleware

### ISSUE THREAD

**Issue by vn38minhtran** [jantimon/favicons-webpack-plugin#5]
When i access path `http://localhost:3000/favicons/apple-touch-icon-57x57.png` it response `Cannot GET /favicons/apple-touch-icon-57x57.png `.

**Comment by jantimon** [comment]
Okay I guess that's because the files aren't emitted when loaded from cache - will be fixed soon

**Comment by jantimon** [comment]
I believe @numical is working on something already

**Comment by numical** [comment]
Yup - but it has grown arms and legs!  Aka - my 'two day' estimate is rubbish.  Sometime next week...

**Comment by jantimon** [comment]
@vn38minhtran for now you can just turn off the caching

**Comment by jantimon** [comment]
It seems to work:
https://github.com/jantimon/favicons-webpack-plugin/tree/master/example

**Comment by jantimon** [comment]
@vn38minhtran can I close this?

**Comment by vn38minhtran** [comment]
Sorry for slow to respond and thanks!
