### ISSUE TITLE
Favicons generates unwanted color-theme meta

### ISSUE THREAD

**Issue by mehrdad-shokri** [jantimon/favicons-webpack-plugin#50]
I notted that adding ``new FaviconsWebpackPlugin(PATHS.statics + '\\ashojash.png')`` to plugins,  
besides adding fav icons, adds ``theme-color`` meta attribute to generated html-webpack-plugin file with the default value of ``#fff``.  
Is this a desired outcome? And How can I change that?

**Comment by mehrdaad** [comment]
I found that changing ``background`` would solve the problem.  
But there is another problem here:  
``them-color`` is for chrome based browsers.  
this option should also change ``apple-mobile-web-app-status-bar-style`` (which is for safari browsers)  
and ``msapplication-navbutton-color`` (windows phone browser).  
More information [here](http://stackoverflow.com/a/33193739/5277245)

**Comment by laurenskling** [comment]
the `theme-color` is used by parent package `favicons` : https://github.com/haydenbleasel/favicons#usage

I would say, either drop it, or pass the configurable value to it. Now it always returns `#fff`
