### ISSUE TITLE
manifest should be included into html

### ISSUE THREAD

**Issue by budarin** [jantimon/favicons-webpack-plugin#58]
manifest is generated (but the truth is - most of parameters are not applicable) but not included into header also browserconfig.xml is generated and included into html but has wrong path
(for cache bursting I generate icons into folder name like 'icons-[hash:5]' every icon is linked to that directory but browserconfig.xml - is not)

**Comment by kuka-radovan** [comment]
I would like to have a generated manifest in html file too. I saw this request in few issues, but it is still ignored. Is there an option, how to do it automatically to meet the appropriate PWA requirement?

**Comment by BorntraegerMarc** [comment]
Is there any update on this? I have a own `manifest.json` and the one that is generated from this plugin. So they should be able to be merged somehow...

**Comment by ozasadnyy** [comment]
Any updates here?

**Comment by Igor-Vuk** [comment]
Me too. Would really love to have manifest in HTML .

**Comment by nealoke** [comment]
This seems almost vital for when using the PWA `manifest.json` right?

@jantimon ping

**Comment by perevezencev** [comment]
@jantimon ping
