### ISSUE TITLE
`logo` key doesn't support data URIs

### ISSUE THREAD

**Issue by brandonb927** [jantimon/favicons-webpack-plugin#60]
webpack `2.2.0`
favicons-webpack-plugin `0.0.7`

Similar to [this issue](https://github.com/ampedandwired/html-webpack-plugin/issues/549) here, I'm unable to use a data URI for a favicon image. The error below is what is given when trying to do so.

`EntryModuleNotFoundError: Entry module not found: Error: Can't resolve 'data:image/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQEAYAAABPYyMiAAAABmJLR0T///////8JWPfcAAAACXBIWXMAAABIAAAASABGyWs+AAAAF0lEQVRIx2NgGAWjYBSMglEwCkbBSAcACBAAAeaR9cIAAAAASUVORK5CYII=' in '/fake/project/path'`

**Comment by jantimon** [comment]
This would be possible however webpack itself doesn't support base64 images for loaders which would cause a lot of work arounds.

**Comment by brandonb927** [comment]
Thanks for the feedback! I'm not too familiar with how webpack works underneath the hood but this seems like an oversight no? Regardless, I might just use a blank PNG then for this if it's not going to be supported. 

Cheers

**Comment by morewry** [comment]
What do loaders have to do with this? If I want to use a base64 encoded image as a data URI, it doesn't need to run through a loader. It's supported in the browser.
