### ISSUE TITLE
Does favicons-webpack-plugin work with webpack v2?

### ISSUE THREAD

**Issue by didi0613** [jantimon/favicons-webpack-plugin#62]
Hi all,
Does favicons-webpack-plugin work with webpack 2.0? 
If not, can I know what's the plan for updating it? Currently it still goes with webpack 1.3.0.

**Comment by c-h-** [comment]
@didi0613 I'm using it with Webpack 2 (v2.2.1) no problem

**Comment by didi0613** [comment]
@c-h-  Thank you for confirming.
Do you know if favicons-webpack-plugin has plans for upgrading to webpack 2.0?

**Comment by c-h-** [comment]
@didi0613 I'm not involved in this project at all so I'm not sure. Looks like this pull request does what you're looking for though: https://github.com/jantimon/favicons-webpack-plugin/pull/48

Should be no problem to use it like so: `npm install --save-dev https://github.com/LoicMahieu/favicons-webpack-plugin/tree/feature/peer-dependency`

**Comment by didi0613** [comment]
@c-h- Thank you very much

**Comment by xeho91** [comment]
It doesn't work for me either (Webpack v2.2.1).
Using this loader, properly configured throws nothing. No output, no error, nothing.
