### ISSUE TITLE
Hang while bundle building

### ISSUE THREAD

**Issue by kierenj** [jantimon/favicons-webpack-plugin#63]
How can I diagnose this?  The CPU just sits and spins after the 'content is served from (path)' message.

My code:
`const FaviconsWebpackPlugin = require('favicons-webpack-plugin');`
and in the `plugins` array:
`new FaviconsWebpackPlugin('favicon.png'),`

If I remove the plugin, things work just fine.

I am using `HtmlWebpackPlugin` and some others (extract text for css, commons chunk, define).

**Comment by kierenj** [comment]
Resolved by using `new FaviconsWebpackPlugin(__dirname + '/favicon.png'),` instead.  Not sure where it was looking, if not relative to current path?  Worth adding a note in the docs / an error message?

**Comment by Garito** [comment]
a console.log(__dirname) reveals project/build
I'm using resolve('src/asset/image')
