### ISSUE TITLE
Problem scaling icons

### ISSUE THREAD

**Issue by Birowsky** [jantimon/favicons-webpack-plugin#67]
There's a problem downscaling the original graphic:

<img width="276" alt="screen shot 2017-03-21 at 14 29 55" src="https://cloud.githubusercontent.com/assets/3199950/24149448/e4756552-0e42-11e7-9971-d0afe2643bf1.png">

Where does the outline come from? The original 1500x1500 png is free of any artifacts.

**Comment by moimael** [comment]
I have the same issue

**Comment by Birowsky** [comment]
I would like to kindly ask why was this closed?

We're still getting the same problem in version `4.2.0`. Has it since been fixed?

**Comment by Birowsky** [comment]
You can see that [all exports](https://github.com/jantimon/favicons-webpack-plugin/files/6317010/All.exports.zip) have the strange black outline:

![apple-touch-icon-57x57](https://user-images.githubusercontent.com/3199950/114852412-0b70a200-9de3-11eb-81da-bd7dcf577ef7.png)
![apple-touch-icon-120x120](https://user-images.githubusercontent.com/3199950/114852416-0c093880-9de3-11eb-8d92-0a4dae2e4ba4.png)
![apple-touch-icon-precomposed](https://user-images.githubusercontent.com/3199950/114852417-0c093880-9de3-11eb-92a8-5626e049b812.png)
![apple-touch-icon](https://user-images.githubusercontent.com/3199950/114852418-0ca1cf00-9de3-11eb-9152-a488c552cd3b.png)
![favicon-16x16](https://user-images.githubusercontent.com/3199950/114852419-0ca1cf00-9de3-11eb-9e56-69c79eda496d.png)
![favicon-48x48](https://user-images.githubusercontent.com/3199950/114852421-0ca1cf00-9de3-11eb-91cb-dfc527846390.png)
