### ISSUE TITLE
Does not support Windows 10 Tiles

### ISSUE THREAD

**Issue by trajano** [jantimon/favicons-webpack-plugin#69]
Here's a sample

````
    <meta name="msapplication-TileImage" content="assets/logo-144x144.png" />
    <meta name="msapplication-TileColor" content="#216978" />
````

**Comment by trajano** [comment]
It appears that I have to explicitly add `windows: true` to the configuration rather than relying on the defaults.  I presumed it was enabled as per https://github.com/haydenbleasel/favicons#usage

**Comment by trajano** [comment]
Actually there is still  a bug from what I can tell

````
<meta name="msapplication-TileImage" content="mstile-144x144.png">
````
It didn't put in the directory to the icon.

**Comment by trajano** [comment]
Also it is referring to browserconfig.xml which does not get generated.

**Comment by jantimon** [comment]
This sounds rather like an issue with https://github.com/itgalaxy/favicons (the library used by this plugin)
