### ISSUE TITLE
Adding mask icon for Safari pinned tab icons

### ISSUE THREAD

**Issue by BenjaminRCooper** [jantimon/favicons-webpack-plugin#7]
Is it possible to look into adding the mask-icon for Safari, or is it out of scope?

`<link rel='mask-icon' href='my-icon.svg' color='white'>`

**Comment by jantimon** [comment]
This should be easy to add however the html and image conversion is done by the favicons plugin - so if they would add it we could use it also for the favicons webpack plugin

**Comment by BenjaminRCooper** [comment]
Ok, will close here and move to the relevant repo :)
