### ISSUE TITLE
Inject with HtmlWebpackPlugin

### ISSUE THREAD

**Issue by denu5** [jantimon/favicons-webpack-plugin#76]
Question: Is there something that needs to be set up to make automatic injection work? I see that the icon folder is generated but the injections doesnt work. Here the plugin part of my webpack config. 

```
...
plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new FaviconsWebpackPlugin({
        logo: path.resolve(__dirname, 'dist/images/nova.png'),
        inject: true
    }),
    new HtmlWebpackPlugin({
      filename: indexHtmlName,
      template: 'public/index.html',
      inject: 'head',
      hash: true
    })
  ]
...
```

Thanks in advance!

**Comment by jantimon** [comment]
Can you please try to switch the htmlwebpack plugin and the favicons icon plugin?

**Comment by denu5** [comment]
Did it, but it doesn't help. I made some small debugging and it seems the 'html-webpack-plugin-before-html-processing' hook is never called.

```
...
  console.log('1.');
  // Hook into the html-webpack-plugin processing
  // and add the html
  if (self.options.inject) {
      console.log('2.');
    compiler.plugin('compilation', function (compilation) {
        console.log('3.');
      compilation.plugin('html-webpack-plugin-before-html-processing', function (htmlPluginData, callback) {
          console.log('4.');
        if (htmlPluginData.plugin.options.favicons !== false) {
          htmlPluginData.html = htmlPluginData.html.replace(
            /(<\/head>)/i, compilationResult.stats.html.join('') + '$&');
          callback(null, htmlPluginData);
        }
      });
    });
  }
```

Logging:
1.
2.
3.
3.

**Comment by bensampaio** [comment]
I have the exact same problem, is there any solution for this? Or is this project abandoned?

**Comment by vaske** [comment]
@bensampaio `HtmlWebpackPlugin` should be listed in list of plugins before  `FaviconsWebpackPlugin`

**Comment by notgne2** [comment]
Even with them in the correct order, I am not getting any of the definitions in the resulting HTML. Is there currently an issue with this? I don't have a custom template file if that changes anything

**Comment by Konafets** [comment]
Same for me. The built file does not have the favicons injected. Here is my config:

```javascript
  plugins: [
    new HtmlWebpackPlugin({
      title: 'Preview Layout',
      filename: '../components/index.twig',
      showErrors: true,
    }),
    new FaviconsWebpackPlugin({
      logo: 'assets/favicons/JB_192.png',
      cache: true,
      inject: true,
    }),
    new MiniCssExtractPlugin({
      filename: '[name].css',
      chunkFilename: '[id].css',
    }),
  ],
```

**Comment by jantimon** [comment]
@Konafets which versions do you use?

**Comment by Konafets** [comment]
@jantimon The latest versions I got via NPM of both libs.

**Comment by jantimon** [comment]
favicons-webpack-plugin 2.x is compatible with html-webpack-plugin 3.x 

favicons-webpack-plugin 3.x is compatible with html-webpack-plugin 4.x

**Comment by Konafets** [comment]
@jantimon 

> favicons-webpack-plugin 2.x is compatible with html-webpack-plugin 3.x
> favicons-webpack-plugin 3.x is compatible with html-webpack-plugin 4.x

The only thing that happens is that one favicon is inserted into the HTML file. I expect that all different vendor favicons are injected as stated in the README.

This is what I get:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Preview Layout</title>
  <link rel="icon" href="/assets/favicon.png"><meta name="viewport" content="width=device-width, initial-scale=1"><link href="/main.css" rel="stylesheet"></head>
  <body>
  <script src="/main.js"></script></body>
</html>
```

**Comment by brunok** [comment]
I had the same problem. Got it resolved by setting the inject property of **HtmlWebpackPlugin** to true.

    new HtmlWebpackPlugin({
      **inject: true,**
      ...,
      ...,
    })

I am using favicons-webpack-plugin 3.x  with html-webpack-plugin 4.x

**Comment by jantimon** [comment]
@Konafets by default **during development the FaviconsWebpackPlugin will not generate all logos** to keep your webpack bootup time as fast as possible.

For production build you should see more favicons generated.

If you need all favicons already during development you can set the mode:

```js
new FaviconsWebpackPlugin({
    logo: './src/logo.png', // svg works too
    devMode: 'webapp', // optional can be 'webapp' or 'light' - 'light' by default 
})
```

**Comment by vanoMekantsishvili** [comment]
One question regarding `FaviconsWebpackPlugin`: Does anyone knows what kind of resolution should be favicon.png for this plugin? What is the best format for logo [png, jpg...].

**Comment by jantimon** [comment]
Usually people use 512px x 512px

**Comment by binury** [comment]
@jantimon Injection is still not working, just as OP described

**Comment by jantimon** [comment]
@binury please open a new issue with more context
