### ISSUE TITLE
Manifest.json being created but not injected

### ISSUE THREAD

**Issue by BenjaminRCooper** [jantimon/favicons-webpack-plugin#8]
A manifest.json file is created, but it doesn't seem to be injected into the html file. Is their an option Im currently missing?

**Comment by jantimon** [comment]
The manifest is very basic - would it really help to add it?

**Comment by BenjaminRCooper** [comment]
How do you very basic? in terms of what is contained or how to add it manually?

**Comment by jantimon** [comment]
What it contains.

**Comment by thirdwaffle** [comment]
The `manifest.json` file is used by Android Chrome.
https://realfavicongenerator.net/faq#manifest

**Comment by VitaliyVorobey** [comment]
Плагин не вставляет manifest.json в template

**Comment by jantimon** [comment]
Done in #157
