### ISSUE TITLE
Why the webpack always resolve the favicon path from node_modules?

### ISSUE THREAD

**Issue by TomIsion** [jantimon/favicons-webpack-plugin#80]
My webpack settings:

```
output: {
  publicPath: '/'
},
plugins: [
  new FaviconsWebpackPlugin('logo.png'),
]
```

My `logo.png` saved in the root of the project.

![67881270-a8a0-4149-9921-31ae9b9d37c0](https://cloud.githubusercontent.com/assets/17807471/26340576/c56543a2-3fc1-11e7-86bc-3b185fa0607d.png)

So, how can I solve this question?

**Comment by cozarkd** [comment]
I've got the same problem.
Btw I'm not sure about installation:
`var FaviconsWebpackPlugin = require('..');` (example)
vs
`const FaviconsWebpackPlugin = require('favicons-webpack-plugin')`
vs
`let FaviconsWebpackPlugin = require('favicons-webpack-plugin')`

**Comment by cozarkd** [comment]
Nevermind, found the solution in the example:
`new FaviconsWebpackPlugin('./src/my-logo.png'),`
