### ISSUE TITLE
Overwriting manifest.json favicons settings

### ISSUE THREAD

**Issue by katiasmet** [jantimon/favicons-webpack-plugin#88]
Hi there

I'm wondering if it possible to overwrite some of the favicons generator settings. 
F.e. appDescription and display. Right now it doesn't seem to overwrite the default setting. 

My code: 

new FaviconsWebpackPlugin({
      logo: './src/assets/favicon/favicon.png',
      prefix: 'assets/favicon/',
      emitStats: false,
      statsFilename: 'info.json',
      persistentCache: true,
      background: '#fff',
      title: 'this is the title',
      appDescription: 'this is the description',
      display: 'browser',
      icons: {
        android: true,
        appleIcon: true,
        appleStartup: true,
        coast: false,
        favicons: true,
        firefox: true,
        opengraph: false,
        twitter: false,
        yandex: false,
        windows: false,
      },
    })

**Comment by cbrwizard** [comment]
Also having this question

**Comment by frlinw** [comment]
manifest.json integration improvment (use an existing file ? inject the generated file into index?... ) should be the main purpose of this project, it's a must have for lot of people these days.
Maybe there is a hope, maybe not https://github.com/jantimon/favicons-webpack-plugin/issues/92

**Comment by jantimon** [comment]
@frlinw right now @milewski is working intensively on that topic.
There are some blockers which are slowing him down.  

Maybe you could jump in and support us :)  
The manifest.json from the [favicons project](https://github.com/evilebottnawi/favicons) we are using is kind of outdated. 

We would like to move on with the "android manifest" https://github.com/evilebottnawi/favicons/blob/master/config/files.json#L3 but according to @milewski it's very outdated (maybe he can elaborate why) and he is even considering to fork and rewrite favicons with up to date manifest generation.

Maybe we could also write a "wrapper" plugin instead.
What do you think?

**Comment by frlinw** [comment]
Good news! Ready to help after this incoming release

I think this plugin should do the minimum : 
* generate favicons
* inject into index
* transform the icons property of an existing manifest (about this last step, i'm curious to know what you plan to do)

**Comment by milewski** [comment]
@jantimon the "android manifest" they are generating is not outdated, but the "firefox" one, and its missing few "2017" common icons sizes....

and yeahhh keep **favicons-webpack-plugin** to minimal, and leave the work to the favicon library however  there are other problems with that library that forces `favicons-webpack-plugin` to do more work than it should so for that reason i intend to rewrite it.

a few key points in the **favicons lib** are:

- They are generating two (4 actually) manifest files `manifest.json` / `manifest.webapp` (Google/Mozilla) which the **.webapp** has a slight different schema than the **manifest.json** and Mozilla seems to have [killed it already](https://developer.mozilla.org/en-US/docs/Archive/B2G_OS/Firefox_OS_apps/Building_apps_for_Firefox_OS/Manifest)

- As pointed out [here](https://www.w3.org/TR/appmanifest/) the appmanifets is still a working draft and its implementation might change over the time, the current lib has its source code in a way it's hard to conform to any hard changes (hence why i intend to do a rewrite) also, devices are coming and going really fast, the user should have the power to specify which sizes they desire and not wait we to add this once in a while when we get time (currently you have 0 control over this) despiting the fact that you cant really append new data to the generated manifest (as for example add `serviceworker`, `screenshoots` etc...) (you can if you are using it in node trough) 

in my implementation i am doing a deep research on what are the sizes that you actually need and giving reasons why that size exists for example this is a draft schema that i am aiming for a **configuration template**:

```js
// this is not a .manifest file it's just a configuration template draft for a upcoming favicon version 
// implementations/common-browser.json, and there would be one for android, TV, ios, so on...
{
  "description": "Standard icons for most browsers",
  "rel": "icon",
  "icons": [
    {
      "sizes": [16, 32, 48], // yeah .icon can encapsulate more than one icon on a single file
      "name": "favicon.ico",
      "root": true, // place it on the root, i hate to see the /favicon.icon not found 404 request on my logs and browser sometimes!!!
      "mime": "image/x-icon",
      "description": "Standard for most desktop browsers"
    },
    {
      "size": "32x32",
      "name": "favicon-32.png",
      "description": "Standard for most desktop browsers"
    },
    {
      "size": 96,
      "name": "favicon-96.png",
      "description": "Windows shortcut icon"
    }
  ]
}
```

**Comment by jantimon** [comment]
@milewski thanks for the write up.

Maybe we could change it to:

```js
"icons": {
   'favicon.ico' : {
      "sizes": [16, 32, 48], // yeah .icon can encapsulate more than one icon on a single file
      "name": "favicon.ico",
      "root": true, // place it on the root, i hate to see the /favicon.icon not found 404 request on my logs and browser sometimes!!!
      "mime": "image/x-icon",
      "description": "Standard for most desktop browsers"
    },
```

That way it is easier to work with presets and overwrite certain options e.g.

```
"icon-preset": require('favicons-2017-preset'),
"icons": {
  'favicon.ico' : {
     root: false
   }
}
```

How would you determine which icons would be also show up in the manifest.json?

**Comment by milewski** [comment]
> How would you determine which icons would be also show up in the manifest.json?

there are just a few icons that are for browser..  3 to 4 sizes think... all the other lives on manifest only which are targeted to devices (mobile, tv, others...)

that json sample i posted is not related to the `favicons-webpack-plugin` but an idea on the favicon lib, it's something along what they currenly have in here [https://github.com/evilebottnawi/favicons/tree/master/config](https://github.com/evilebottnawi/favicons/tree/master/config)

**Comment by jantimon** [comment]
Yes I understood that it would be part of a different library (that's why I opened https://github.com/evilebottnawi/favicons/issues/186).  
What do you think about the suggested change?

**Comment by katiasmet** [comment]
@jantimon If the plugin is a bit outdated, it seems a good idea to refactor :). The favicons generator seems a good start. I also noticed that https://realfavicongenerator.net/ now has a lighter package with only a few favicons in it :). I didn't test it on every browser yet, but they say it should work on the most common ones.
