### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by minhtranite** [jantimon/favicons-webpack-plugin#9]
- Missing `<link rel="manifest" href="/path/to/manifest.json">` in html output.
- Missing `<link rel="yandex-tableau-widget" href="/path/to/yandex-browser-manifest.json">` in html output.
- `msapplication-TileImage`, `msapplication-config`, `twitter:image`, `og:image` wrong path.
- Can you support absolute URL for OpenGraph, Twitter image ?

My config:

``` js
new FaviconsWebpackPlugin({
      logo: path.join(__dirname, 'app/assets/images/favicon.png'),
      //prefix: 'favicons/',
      persistentCache: true,
      inject: true,
      icons: {
        android: true,
        appleIcon: true,
        appleStartup: true,
        coast: true,
        favicons: true,
        firefox: true,
        opengraph: true,
        twitter: true,
        yandex: true,
        windows: true
      }
    })
``
```

**Comment by jantimon** [comment]
Thanks for your feedback 👍 
For a absolute url you would have to specify an absolute public path.

Why is the path of msapplication-TileImage, msapplication-config, twitter:image, og:image wrong?

**Comment by vn38minhtran** [comment]
In my html output:
```html
...
<link rel="shortcut icon" href="/37fe8322b169ddbdeabf75930e886ac6/favicon.ico">
<meta name="msapplication-TileColor" content="#fff">
<meta name="msapplication-TileImage" content="mstile-144x144.png">
<meta name="msapplication-config" content="browserconfig.xml">
<meta property="twitter:image" content="twitter.png">
<meta property="og:image" content="open-graph.png">
...
```
I think it will be starts with `prefix` like: `/37fe8322b169ddbdeabf75930e886ac6/mstile-144x144.png`

**Comment by jantimon** [comment]
Oh right - it replaces only href not content...
