### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by wallzero** [jantimon/favicons-webpack-plugin#91]
It would appear the plugin does not always reproduce the same `index.html`. In my tests it seems the assets are asynchronously processed and appended to the `index.html` in varying orders. Is this accurate? Could a mechanism be added to ensure reproducible builds? Thanks!

**Comment by jantimon** [comment]
We could sort by name

**Comment by jantimon** [comment]
This sounds rather like an issue with https://github.com/itgalaxy/favicons (the library used by this plugin)
