### ISSUE TITLE
Webpack 1.0.0

### ISSUE THREAD

**Issue by milewski** [jantimon/favicons-webpack-plugin#92]
Is the owner still active on this repository? i remade the entire code from the ground up closing many issues, simplifying redundant code and upgrading everything to the latest version....

as i can see there are many issues without resolution and also many pull requests without any replies... are you intending in continuing this plugin or are you able to transfer its ownership? i'm almost finishing with the tests and will send a pull request... 

if you wanna transfer it i am okay to maintain it.

**Comment by mastilver** [comment]
Hi @milewski 

I will reach out on private to @jantimon about it

I think it would be better to build a team around this plugin rather than a single person taking care of it

> i remade the entire code from the ground up closing many issues, simplifying redundant code and upgrading everything to the latest version

Can you link to your repo, I couldn't find anything! :)

**Comment by milewski** [comment]
@mastilver hey i just pushed the code at the current state to my repository... still missing polishing up the tests... add a few more tests... add semantic-release.. commitizen... rewrite the Readme... point which issues it fixes... which i will can be finishing by the end of Saturday :)

**Comment by jantimon** [comment]
Well the favicons-webpack-plugin is rather a proc.

After a lot of iterations the vision is quite clear what the common requirements for this plugin look like.

Right now I am searching among some known developers to start a rewrite according to the streamlined specs.

**Comment by milewski** [comment]
@jantimon sure wanna join :) 

Currently i am working a project i needed this icon generation and there were some "points" which i wanted to improve to make it more reasonable for my needs so i forked this version... and ended up "converting everything to typescript" i think generally in the end it`s much cleaner than before and easy to understand what is happening behind the scene...

[https://github.com/milewski/favicons-webpack-plugin/tree/master/source](https://github.com/milewski/favicons-webpack-plugin/tree/master/source)

i haven't changed the "core functionality" per saying... although i changed the options that can be passed to the loader as seen here [PluginOptionsInterface.ts](https://github.com/milewski/favicons-webpack-plugin/blob/master/source/Interfaces/PluginOptionsInterface.ts)

**Comment by jantimon** [comment]
@milewski I am a big fan of typescript but I am not sure if it is a good fit for a webpack plugin.

You add a lot of complexity (like building before testing, building before publishing, stacktraces of the plugin won't match the typescript code) and it will also decrease the amount of people who can submit pull requests.

Do you have time for a short chat?
https://gitter.im/webpack/webpack/developer

**Comment by jantimon** [comment]
Current draft of the upcoming api:

```
{ 
     source: string,
     icons?: 'dev' | 'default' | 'full' | Object, //(maybe there is a definition for https://www.npmjs.com/package/favicons options.icons)
     mainfest?: 'string' | true | false, // string would be a path to the manifest file relative to the webpack compiler context - default: true
     inject?: boolean, // wether it should try to add it to html-webplugin - default true
     export?: string, // where the information about the assets should be exported to
     faviconsOptions?: Object  // https://www.npmjs.com/package/favicons options except icons 
}
```

Main conceptional changes:

+ if a manifest path is specified the information will be merged with the manifest from [favicons](https://github.com/evilebottnawi/favicons) 
+ we will entirely remove the caching (because it is hard to maintain and to complex) as long as webpack does not offer a caching solution

**Comment by frlinw** [comment]
It seems to be clean !

1 - "prefix" property disappeared so ?
A ```name``` property like ```name : [name].[hash].[ext]``` is still a nice to have

2 - In some cases (?) is favicons able to generate its (outdated) manifest.json ?

 (your wrote "mainfest")

**Comment by jantimon** [comment]
Thanks @frlinw updated that

**Comment by damianobarbati** [comment]
@jantimon that's great news,
. when do you think you'll release a stable beta?
. can `favicons-webpack-plugin` be used to generate splashscreen as well (useful for cordova!)?
. is `extract-text-plugin` required? Because without it I get the following:
```
$ NODE_ENV=development webpack --config ./config/webpack.config.js --progress --watch
module.js:491
    throw err;
    ^

Error: Cannot find module 'extract-text-webpack-plugin'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/damz/Desktop/react-app/config/webpack.config.js:11:27)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at module.exports (/Users/damz/Desktop/react-app/node_modules/favicons-webpack-plugin/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/Users/damz/Desktop/react-app/node_modules/favicons-webpack-plugin/node_modules/webpack/bin/webpack.js:39:40)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
error Command failed with exit code 1.
```

**Comment by Janekk** [comment]
@jantimon is it possible to make a release with bumped up Webpack dependency to >= 2? (while you are still working on the new API?)

**Comment by StephanBijzitter** [comment]
@jantimon please don't name options after "reserved" keywords (like export). My ESLint configuration will want to kill me if using that option.

**Comment by brunocodutra** [comment]
@jantimon @milewski any updates on this? 

The draft for the upcoming API looks great, in fact I was desperately in need of something just like it and ended up [forking this project](https://github.com/brunocodutra/webapp-webpack-plugin) and tailoring it to my needs.

What's left feels like a step closer to what you propose: I scraped the cache functionality, exposed all configuration options provided by Favicons and updated dependencies. 

Please let me know if you feel my fork could serve as a starting ground for the upcoming API, I'd gladly contribute my changes back.

**Comment by Vinnl** [comment]
Supposedly 0.0.8 now supports Webpack 4: https://github.com/jantimon/favicons-webpack-plugin/blob/master/CHANGELOG.md
