### ISSUE TITLE
start_url and orientation not used in generated manifest?

### ISSUE THREAD

**Issue by nealoke** [jantimon/favicons-webpack-plugin#94]
I'm currently using this great plugin however I've seen that even though I've set the `start_url` and `orientation` it is not used in the outputted `manifest.json` 

**Used config**
```
new FaviconsWebpackPlugin({
	logo: "../src/assets/icons/icon.png",
	prefix: "assets/icons/[hash]/",
	title: "Wizer App",
	appName: "Wizer App",
	appDescription: "Wizer application for capturing feedback",
	developerName: "Wizer",
	developerURL: "http://www.wizer.be/",
	background: "#fff",
	theme_color: "#59b4ca",
	display: "fullscreen",
	orientation: "portrait",
	start_url: "/",
	version: "1.0",
	logging: true,
	inject: true,
	persistentCache: true,
	emitStats: false,
	icons: {
		android: { offset: 7 },
		appleIcon: { offset: 7 },
		appleStartup: { offset: 7 },
		coast: false,
		favicons: true,
		firefox: { offset: 7 },
		opengraph: { offset: 7 },
		twitter: true,
		yandex: false,
		windows: false
	}
})
```

**Output `manifest.json`**
```
{
  "name": "Wizer App",
  "short_name": "Wizer App",
  "description": null,
  "dir": "auto",
  "lang": "en-US",
  "display": "standalone",
  "orientation": "any",
  "start_url": "/?homescreen=1",
  "background_color": "#fff",
  "icons": [
     // icons
  ]
}
```

**Comment by kronos93** [comment]
Hello, you can try with this fork: https://www.npmjs.com/package/favicons-webpack-plugin-cesco
Only install npm i favicons-webpack-plugin-cesco
And config like this:
new FaviconsWebpackPlugin({
    // Your source logo 
    logo: 'my-logo.png',
    // The prefix for all image files (might be a folder or a name) 
    prefix: 'icons-[hash]/',
    // Emit all stats of the generated icons 
    emitStats: false,
    // The name of the json containing all favicon information 
    statsFilename: 'iconstats-[hash].json',
    // Generate a cache file with control hashes and 
    // don't rebuild the favicons until those hashes change 
    persistentCache: true,
    // Inject the html into the html-webpack-plugin 
    inject: true,
    // favicons config (see https://github.com/haydenbleasel/favicons#usage) 
    config: {
      appName: 'App Name',
      appDescription: 'App description',
      appleStatusBarStyle: 'black-translucent',
      background: "#fff",
      theme_color: "#fff",
      lang: 'en-US',
      display: "standalone",
      orientation: "portrait",
      start_url: "/?homescreen=1",
      icons: {
        android: true,              // Create Android homescreen icon. `boolean` or `{ offset, background, shadow }` 
        appleIcon: true,            // Create Apple touch icons. `boolean` or `{ offset, background }` 
        appleStartup: true,         // Create Apple startup images. `boolean` or `{ offset, background }` 
        coast: { offset: 25 },      // Create Opera Coast icon with offset 25%. `boolean` or `{ offset, background }` 
        favicons: true,             // Create regular favicons. `boolean` 
        firefox: true,              // Create Firefox OS icons. `boolean` or `{ offset, background }` 
        windows: true,              // Create Windows 8 tile icons. `boolean` or `{ background }` 
        yandex: true                // Create Yandex browser icon. `boolean` or `{ background }` 
      }
    }
  })

**Comment by Friksel** [comment]
Why is this issue closed? It still doesn't seem to work in in december 2020 now...

The `start_url` is now always `"/?homescreen=1"` in the manifest.json, but that doesn't make sense at all to me so I'd like to change it.

Could the `start_url` be build into the webpack plugin config?

**Comment by skedwards88** [comment]
For anyone else looking, this works for me:

```
new FaviconsWebpackPlugin({
      logo: "./src/images/favicon.png", // svg works too!
      mode: "webapp", // optional can be 'webapp', 'light' or 'auto' - 'auto' by default
      devMode: "webapp", // optional can be 'webapp' or 'light' - 'light' by default
      favicons: {
        appName: "my-app",
        start_url: ".",
        appDescription: "My awesome App",
        developerName: "Me",
        developerURL: null, // prevent retrieving from the nearest package.json
        background: "#ddd",
        theme_color: "#333",
        icons: {
          coast: false,
          yandex: false,
        },
      },
    })```

webpack version 5.52.0
favicons-webpack-plugin version 5.0.2
