### ISSUE TITLE
Add support for El Capitan on Mac

### ISSUE THREAD

**Issue by awentzel** [jantimon/favicons-webpack-plugin#96]
- The mask icon for Safari pinned tabs is absent
- The mask icon has no color

iconstats.json should include in HTML and create the SVG in the correct `icons/` folder at 215x215 dimensions.

```html
 <link rel="mask-icon" href="/icons/safari-pinned-tab.svg" color="#5bbad5"> 
```

**Comment by asakalou** [comment]
Hello, are there any updates regarding this issue?

**Comment by erosa** [comment]
This plugin uses [favicons](https://github.com/itgalaxy/favicons/) to generate icons. See the README:

> Why are you missing certain favicons?

> Because pure Javascript modules aren't available at the moment. For example, the El Capitan SVG favicon and the Windows tile silhouette ability both require SVG support. If modules for these task begin to appear, please jump on the appropriate issue and we'll get on it ASAP.

You can also check out [this issue](https://github.com/itgalaxy/favicons/issues/61) on that issue.
